-- 报关资料 Excel 商品明细表（幂等建表，不删除已有数据）
USE export_tax_refund;

CREATE TABLE IF NOT EXISTS customs_declaration_excel_item (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '报关资料Excel商品明细主键',
    contract_agreement_no VARCHAR(100) NOT NULL COMMENT '合同协议号',
    product_sequence_no VARCHAR(20) NOT NULL COMMENT '原始项号',
    product_sequence_normalized VARCHAR(20) NOT NULL COMMENT '标准化项号',
    export_invoice_no VARCHAR(100) NULL COMMENT '报关资料商业发票号码',
    customs_declaration_no VARCHAR(30) NULL COMMENT '匹配后的海关编号',
    commodity_code VARCHAR(20) NULL COMMENT '商品编码',
    product_name VARCHAR(500) NULL COMMENT '商品名称',
    sku VARCHAR(200) NULL COMMENT '标准化SKU',
    specification_model VARCHAR(500) NULL COMMENT '规格型号',
    transaction_quantity DECIMAL(20,6) NULL,
    transaction_unit VARCHAR(50) NULL,
    statutory_quantity DECIMAL(20,6) NULL,
    statutory_unit VARCHAR(50) NULL,
    unit_price DECIMAL(20,8) NULL,
    total_price DECIMAL(20,2) NULL,
    currency_code VARCHAR(10) NULL,
    format_version VARCHAR(30) NOT NULL,
    source_file_name VARCHAR(255) NOT NULL,
    source_file_hash CHAR(64) NOT NULL,
    source_row_no INT NOT NULL,
    import_batch_id BIGINT NULL,
    parse_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    parse_message VARCHAR(1000) NULL,
    pdf_match_status VARCHAR(30) NOT NULL DEFAULT 'UNMATCHED',
    pdf_import_batch_id BIGINT NULL,
    pdf_source_page_no INT NULL,
    matched_at DATETIME(3) NULL,
    is_current TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    deleted_by VARCHAR(64) NULL,
    deleted_at DATETIME(3) NULL,
    created_by VARCHAR(64) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_cdei_contract_item (contract_agreement_no, product_sequence_normalized),
    KEY idx_cdei_customs_no (customs_declaration_no),
    KEY idx_cdei_sku (sku),
    KEY idx_cdei_file_hash (source_file_hash),
    KEY idx_cdei_pdf_match (pdf_match_status),
    KEY idx_cdei_import_batch (import_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='报关资料Excel商品明细表';
