from contextlib import contextmanager
from datetime import date, datetime
from pathlib import Path
from unittest.mock import MagicMock

import pytest

from backend.services import weekly_inventory_sync_service as sync
from backend.services import weekly_inventory_export_service as export
from backend.repositories import weekly_inventory_repository as repo


def row(**changes):
    return dict(dict(wid=18678, whb_id=59911, product_id=403591, sku='FCA-50457-0695',
                     store_id='0', msku='', fnsku='', total=10, lockNum=10, validNum=0), **changes)


def normalize(bins):
    return sync.normalize(
        [dict(wid=18678, product_id=403591, sku='FCA-50457-0695', product_total=10, purchase_price='1')],
        bins, [dict(id=403591, product_name='产品')], date(2026, 9, 10), 'batch', datetime.now(),
    )


def test_real_case_keeps_both_stores_and_export_does_not_double_count():
    sources = [row(), row(store_id='12633', total=0, lockNum=0)]
    groups = normalize(sources)
    assert len(groups['bins']) == 2
    assert [r['raw_json'] for r in groups['bins']] == sources
    assert [r['store_id'] for r in groups['bins']] == ['0', '12633']
    headers, records = export.build_rows(groups, {18678: 'CTUAMZ-US1中转仓'})
    assert len(records) == 1
    output = dict(zip(headers, records[0]))
    assert output['锁定量(仓位)'] == 10
    assert output['未锁定量(仓位)'] == 0
    assert output['实际库存总量'] == 10
    assert output['库存金额'] == 10


@pytest.mark.parametrize('field', ['store_id', 'msku', 'fnsku'])
def test_each_additional_identity_dimension_is_preserved(field):
    assert len(normalize([row(), row(**{field: 'different'})])['bins']) == 2


def test_msku_case_spaces_and_framing_are_exact():
    sources = [row(msku='abc'), row(msku='ABC'), row(msku='abc '),
               row(msku='a:b', fnsku='c'), row(msku='a', fnsku='b:c')]
    assert len(normalize(sources)['bins']) == len(sources)


@pytest.mark.parametrize('second', [row(), row(total=0, lockNum=0),
                                  row(store_id=None, msku=None, fnsku=None),
                                  row(store_id='  ', msku=None), row(store_id=0)])
def test_full_key_duplicates_including_missing_keys_still_fail(second):
    with pytest.raises(ValueError, match='完整业务键重复'):
        normalize([row(), second])


def test_no_source_fields_rewritten_for_null_or_case():
    source = row(store_id=None, msku=None, fnsku='fNsKu')
    item = normalize([source])['bins'][0]
    assert item['store_id'] is None and item['msku'] is None and item['fnsku'] == 'fNsKu'
    assert item['raw_json'] == source
    assert 'bin_identity_key' not in item  # generated by MySQL, not application INSERT


def schema_rows():
    return [dict(COLUMN_TYPE='varbinary(1600)', EXTRA='STORED GENERATED',
                 COLUMN_COMMENT=repo.BIN_IDENTITY_COMMENT),
            dict(index_columns=repo.BIN_INDEX_COLUMNS, non_unique=0, prefix_parts=0)]


@pytest.mark.parametrize('case', ['valid', 'missing', 'old_index', 'prefix', 'non_unique', 'ordinary_column'])
def test_schema_preflight(monkeypatch, case):
    rows = schema_rows()
    if case == 'missing': rows = [None]
    if case == 'old_index': rows[1]['index_columns'] = 'snapshot_date,sync_batch_id,wid,whb_id,product_id'
    if case == 'prefix': rows[1]['prefix_parts'] = 1
    if case == 'non_unique': rows[1]['non_unique'] = 1
    if case == 'ordinary_column': rows[0]['EXTRA'] = ''
    connection = MagicMock()
    cursor = connection.cursor.return_value.__enter__.return_value
    cursor.fetchone.side_effect = rows
    @contextmanager
    def connect(): yield connection
    monkeypatch.setattr(repo, 'db_connection', connect)
    if case == 'valid': repo.require_bin_identity_schema()
    else:
        with pytest.raises(ValueError, match='10_周报仓位业务键修复.sql'):
            repo.require_bin_identity_schema()
    assert all(c.args[0].startswith('SELECT') for c in cursor.execute.call_args_list)


def test_missing_migration_fails_before_any_lingxing_call(monkeypatch, tmp_path):
    factory, insert, finish = MagicMock(), MagicMock(), MagicMock()
    monkeypatch.setattr(sync, 'LingXingClient', factory)
    monkeypatch.setattr(export, 'export_root', lambda: tmp_path)
    monkeypatch.setattr(repo, 'begin_export', MagicMock())
    monkeypatch.setattr(repo, 'finish_export', finish)
    monkeypatch.setattr(repo, 'insert_snapshot', insert)
    monkeypatch.setattr(repo, 'require_bin_identity_schema', MagicMock(side_effect=ValueError('执行10_周报仓位业务键修复.sql')))
    with pytest.raises(ValueError, match='执行10'):
        sync.sync_weekly_inventory()
    factory.assert_not_called()
    insert.assert_not_called()
    finish.assert_called_once()


def test_new_schema_and_migration_include_exact_generated_key_without_data_deletes():
    import re
    base = Path(__file__).parents[1]
    migration = (base/'migrations/20260910_weekly_bin_identity.sql').read_text(encoding='utf-8')
    schema = (base/'backend/schema.sql').read_text(encoding='utf-8')
    assert repo.BIN_IDENTITY_COMMENT in migration and repo.BIN_IDENTITY_COMMENT in schema
    assert 'VARBINARY(1600) GENERATED ALWAYS AS' in migration
    assert 'CHAR_LENGTH(COALESCE(`msku`' in migration
    assert 'CHAR_LENGTH(COALESCE(`fnsku`' in migration
    assert repo.BIN_INDEX_COLUMNS in migration
    assert 'v_before <> v_after' in migration
    assert 'Unexpected uk_bin_week definition' in migration
    assert not re.search(r'\b(?:DELETE\s+FROM|TRUNCATE|DROP\s+TABLE|UPDATE\s+ods_)', migration, re.I)
    old = (base/'migrations/20260909_weekly_inventory.sql').read_text(encoding='utf-8')
    assert "IN ('snapshot_date,sync_batch_id,wid,whb_id,product_id','" + repo.BIN_INDEX_COLUMNS + "')" in old
