CREATE TABLE IF NOT EXISTS ads_monthly_opening_inventory_value (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  batch_id VARCHAR(64) NOT NULL COMMENT 'ETL批次ID',
  report_date DATE NOT NULL COMMENT '期初库存日期，通常为每月1日',
  source_system VARCHAR(32) NOT NULL COMMENT '数据来源系统：LINGXING/AMZ/EBAY',
  platform VARCHAR(32) NOT NULL COMMENT '平台：LINGXING/AMZ/EBAY',
  warehouse_type VARCHAR(32) NOT NULL COMMENT '仓库类型：LOCAL本地仓/OVERSEAS海外仓/FBA亚马逊仓/AWD仓',
  warehouse_type_name VARCHAR(100) NULL COMMENT '仓库类型名称',
  sys_wid BIGINT NOT NULL DEFAULT 0 COMMENT '来源系统仓库ID，空值归一为0',
  warehouse_name VARCHAR(255) NULL COMMENT '仓库名称',
  seller_name VARCHAR(255) NULL COMMENT '店铺名称',
  sku VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'SKU，空值归一为空字符串',
  fnsku VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'FNSKU，空值归一为空字符串',
  spu VARCHAR(128) NULL COMMENT 'SPU',
  product_name VARCHAR(500) NULL COMMENT '商品名称',
  brand VARCHAR(255) NULL COMMENT '品牌名称',
  category1 VARCHAR(255) NULL COMMENT '一级类目名称',
  category2 VARCHAR(255) NULL COMMENT '二级类目名称',
  category3 VARCHAR(255) NULL COMMENT '三级类目名称',
  opening_qty DECIMAL(18,4) NULL COMMENT '期初库存数量',
  opening_cost DECIMAL(18,4) NULL COMMENT '期初库存成本',
  unit_cost DECIMAL(18,6) NULL COMMENT '期初单位成本：opening_cost/opening_qty',
  cost_status VARCHAR(32) NOT NULL COMMENT '成本检查状态：OK/ZERO_COST/ZERO_QTY/MISSING_COST',
  anomaly_flag TINYINT NOT NULL DEFAULT 0 COMMENT '是否异常：1异常 0正常',
  anomaly_reason VARCHAR(255) NULL COMMENT '异常原因说明',
  source_ods_id BIGINT NULL COMMENT '来源ODS记录ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ads_opening_inv (
    report_date,
    source_system,
    warehouse_type,
    sys_wid,
    sku,
    fnsku
  ),
  KEY idx_report_status (report_date, cost_status),
  KEY idx_report_warehouse (report_date, warehouse_type, sys_wid),
  KEY idx_sku (sku)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='月初期初库存货值检查结果表';
