-- 目标库：Date-Project（Python 数据库）。不要在 jmh_data_platform 执行。
-- 月度库存报表清洗明细、分维度汇总和部门主表；所有表及字段均使用中文注释。

CREATE TABLE IF NOT EXISTS `dwd_inventory_report_fba_detail` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `stat_month` CHAR(7) NOT NULL COMMENT '数据归属年月，格式YYYY-MM',
    `source_id` BIGINT UNSIGNED NOT NULL COMMENT 'FBA库存ODS源表主键',
    `source_child_index` INT NOT NULL DEFAULT 0 COMMENT 'ODS子明细序号，非嵌套明细为0',
    `sync_batch_id` VARCHAR(64) NOT NULL COMMENT '源数据同步批次ID',
    `sid` VARCHAR(32) NULL COMMENT '领星店铺SID',
    `store_name` VARCHAR(255) NULL COMMENT 'ERP店铺名称',
    `group_code` VARCHAR(32) NULL COMMENT '库存归属组别',
    `department_code` VARCHAR(32) NULL COMMENT '汇总部门编码',
    `principal_name` VARCHAR(100) NOT NULL DEFAULT '未分配' COMMENT '负责人姓名',
    `principal_match_source` VARCHAR(32) NOT NULL DEFAULT 'UNMATCHED' COMMENT '负责人匹配来源',
    `ware_house_name` VARCHAR(255) NULL COMMENT '领星仓库名称',
    `msku` VARCHAR(255) NULL COMMENT '亚马逊卖家SKU（MSKU）',
    `asin` VARCHAR(64) NULL COMMENT '亚马逊商品标识码（ASIN）',
    `fnsku` VARCHAR(255) NULL COMMENT '亚马逊配送网络SKU（FNSKU）',
    `local_sku` VARCHAR(255) NULL COMMENT '本地商品SKU',
    `local_name` VARCHAR(1000) NULL COMMENT '本地商品名称',
    `country_code` VARCHAR(32) NULL COMMENT '国家或站点编码',
    `end_inventory_qty` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '期末库存含移仓数量',
    `end_inventory_total_cost` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '期末库存含移仓总成本',
    `end_in_transit_qty` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '期末在途数量',
    `end_in_transit_total_cost` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '期末在途总成本',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_inventory_fba_month_source` (`stat_month`,`source_id`,`source_child_index`),
    KEY `idx_inventory_fba_month_department` (`stat_month`,`department_code`),
    KEY `idx_inventory_fba_month_owner` (`stat_month`,`principal_name`),
    KEY `idx_inventory_fba_month_sid` (`stat_month`,`sid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='DWD-领星FBA月度库存报表清洗明细';

CREATE TABLE IF NOT EXISTS `dwd_inventory_report_overseas_detail` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `stat_month` CHAR(7) NOT NULL COMMENT '数据归属年月，格式YYYY-MM',
    `source_id` BIGINT UNSIGNED NOT NULL COMMENT '海外仓库存ODS源表主键',
    `source_child_index` INT NOT NULL DEFAULT 0 COMMENT 'ODS子明细序号，非嵌套明细为0',
    `sync_batch_id` VARCHAR(64) NOT NULL COMMENT '源数据同步批次ID',
    `sys_wid` VARCHAR(32) NULL COMMENT '领星系统仓库ID',
    `ware_house_name` VARCHAR(255) NULL COMMENT '领星仓库名称',
    `seller_name` VARCHAR(255) NULL COMMENT '店铺或卖家名称',
    `product_name` VARCHAR(1000) NULL COMMENT '商品名称',
    `sku` VARCHAR(255) NULL COMMENT '商品SKU',
    `fnsku` VARCHAR(255) NULL COMMENT '亚马逊配送网络SKU（FNSKU）',
    `spu` VARCHAR(255) NULL COMMENT '标准产品单元（SPU）',
    `api_sku` VARCHAR(255) NULL COMMENT '第三方库存SKU',
    `brand` VARCHAR(255) NULL COMMENT '商品品牌',
    `platform_code` VARCHAR(16) NOT NULL COMMENT '平台编码：AMZ或EBAY',
    `group_code` VARCHAR(32) NULL COMMENT '库存归属组别',
    `department_code` VARCHAR(32) NULL COMMENT '汇总部门编码',
    `principal_name` VARCHAR(100) NOT NULL DEFAULT '未分配' COMMENT '负责人姓名',
    `principal_match_source` VARCHAR(32) NOT NULL DEFAULT 'UNMATCHED' COMMENT '负责人匹配来源',
    `end_in_transit_qty` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '期末在途数量',
    `end_in_transit_total_cost` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '期末在途总成本',
    `end_inventory_qty` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '期末库存数量',
    `end_inventory_total_cost` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '期末库存总成本',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_inventory_overseas_month_source` (`stat_month`,`source_id`,`source_child_index`),
    KEY `idx_inventory_overseas_month_department` (`stat_month`,`department_code`),
    KEY `idx_inventory_overseas_month_owner` (`stat_month`,`principal_name`),
    KEY `idx_inventory_overseas_month_wid` (`stat_month`,`sys_wid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='DWD-领星海外仓月度库存报表清洗明细';

CREATE TABLE IF NOT EXISTS `dwd_inventory_report_local_detail` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `stat_month` CHAR(7) NOT NULL COMMENT '数据归属年月，格式YYYY-MM',
    `source_id` BIGINT UNSIGNED NOT NULL COMMENT '本地仓库存ODS源表主键',
    `source_child_index` INT NOT NULL DEFAULT 0 COMMENT 'ODS子明细序号，非嵌套明细为0',
    `sync_batch_id` VARCHAR(64) NOT NULL COMMENT '源数据同步批次ID',
    `sys_wid` VARCHAR(32) NULL COMMENT '领星系统仓库ID',
    `ware_house_name` VARCHAR(255) NULL COMMENT '领星仓库名称',
    `seller_name` VARCHAR(255) NULL COMMENT '店铺或卖家名称',
    `product_name` VARCHAR(1000) NULL COMMENT '商品名称',
    `sku` VARCHAR(255) NULL COMMENT '商品SKU',
    `fnsku` VARCHAR(255) NULL COMMENT '亚马逊配送网络SKU（FNSKU）',
    `spu` VARCHAR(255) NULL COMMENT '标准产品单元（SPU）',
    `brand` VARCHAR(255) NULL COMMENT '商品品牌',
    `platform_code` VARCHAR(16) NOT NULL COMMENT '平台编码：AMZ或EBAY',
    `group_code` VARCHAR(32) NULL COMMENT '库存归属组别',
    `department_code` VARCHAR(32) NULL COMMENT '汇总部门编码',
    `principal_name` VARCHAR(100) NOT NULL DEFAULT '未分配' COMMENT '负责人姓名',
    `principal_match_source` VARCHAR(32) NOT NULL DEFAULT 'UNMATCHED' COMMENT '负责人匹配来源',
    `end_in_transit_qty` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '期末在途数量',
    `end_in_transit_total_cost` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '期末在途总成本',
    `end_inventory_qty` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '期末库存数量',
    `end_inventory_total_cost` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '期末库存总成本',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_inventory_local_month_source` (`stat_month`,`source_id`,`source_child_index`),
    KEY `idx_inventory_local_month_department` (`stat_month`,`department_code`),
    KEY `idx_inventory_local_month_owner` (`stat_month`,`principal_name`),
    KEY `idx_inventory_local_month_wid` (`stat_month`,`sys_wid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='DWD-领星本地仓月度库存报表清洗明细';

CREATE TABLE IF NOT EXISTS `dws_inventory_report_dimension_summary` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `stat_month` CHAR(7) NOT NULL COMMENT '数据归属年月，格式YYYY-MM',
    `source_type` VARCHAR(16) NOT NULL COMMENT '来源类型：FBA、OVERSEAS或LOCAL',
    `platform_code` VARCHAR(16) NOT NULL COMMENT '平台编码：AMZ或EBAY',
    `dimension_type` VARCHAR(16) NOT NULL COMMENT '汇总维度：GROUP、OWNER或WAREHOUSE',
    `dimension_value` VARCHAR(255) NOT NULL COMMENT '组别、负责人或仓库名称',
    `department_code` VARCHAR(32) NULL COMMENT '汇总部门编码',
    `source_rows` INT NOT NULL DEFAULT 0 COMMENT '参与汇总的明细行数',
    `end_in_transit_qty` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '期末在途数量汇总',
    `end_in_transit_total_cost` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '期末在途总成本汇总',
    `end_inventory_qty` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '期末库存数量汇总',
    `end_inventory_total_cost` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '期末库存总成本汇总',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_inventory_dimension` (`stat_month`,`source_type`,`platform_code`,`dimension_type`,`dimension_value`,`department_code`),
    KEY `idx_inventory_dimension_month_department` (`stat_month`,`department_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='DWS-月度库存报表来源维度汇总';

CREATE TABLE IF NOT EXISTS `dws_inventory_report_department_summary` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `stat_month` CHAR(7) NOT NULL COMMENT '数据归属年月，格式YYYY-MM',
    `department_code` VARCHAR(32) NOT NULL COMMENT '部门编码',
    `department_name` VARCHAR(64) NOT NULL COMMENT '部门显示名称',
    `display_order` INT NOT NULL COMMENT '页面显示顺序',
    `is_total` TINYINT NOT NULL DEFAULT 0 COMMENT '是否汽配小计行：0否，1是',
    `local_end_in_transit_qty` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '本地仓期末在途数量',
    `local_end_in_transit_total_cost` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '本地仓期末在途总成本',
    `local_end_inventory_qty` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '本地仓期末库存数量',
    `local_end_inventory_total_cost` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '本地仓期末库存总成本',
    `overseas_end_in_transit_qty` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '海外仓期末在途数量',
    `overseas_end_in_transit_total_cost` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '海外仓期末在途总成本',
    `overseas_end_inventory_qty` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '海外仓期末库存数量',
    `overseas_end_inventory_total_cost` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '海外仓期末库存总成本',
    `fba_end_inventory_qty` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT 'FBA仓期末库存含移仓数量',
    `fba_end_inventory_total_cost` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT 'FBA仓期末库存含移仓总成本',
    `fba_end_in_transit_qty` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT 'FBA仓期末在途数量',
    `fba_end_in_transit_total_cost` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT 'FBA仓期末在途总成本',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_inventory_department_month` (`stat_month`,`department_code`),
    KEY `idx_inventory_department_month_order` (`stat_month`,`display_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='DWS-月度库存报表部门主表';
