-- 目标库：Date-Project（Python 数据库）。不要在 jmh_data_platform 执行。
-- 三张表只保存领星库存报表源数据，暂不包含 DWD/DWS 清洗统计逻辑。

CREATE TABLE IF NOT EXISTS `ods_lingxing_fba_monthly_inventory_detail` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `stat_month` CHAR(7) NOT NULL COMMENT '数据归属年月，格式YYYY-MM',
    `sync_batch_id` VARCHAR(64) NOT NULL COMMENT '本次同步批次ID',
    `query_start_date` VARCHAR(10) NOT NULL COMMENT '本次接口查询开始日期',
    `query_end_date` VARCHAR(10) NOT NULL COMMENT '本次接口查询结束日期',
    `request_scope_json` JSON NOT NULL COMMENT '本次请求的seller_id店铺范围（JSON）',
    `source_page` INT NOT NULL DEFAULT 1 COMMENT '接口来源页码',
    `source_offset` INT NOT NULL DEFAULT 0 COMMENT '接口来源偏移量',
    `source_row_no` INT NOT NULL DEFAULT 0 COMMENT '同步批次内原始行号',
    `api_code` VARCHAR(32) NULL COMMENT '接口返回状态码',
    `api_message` TEXT NULL COMMENT '接口返回提示信息',
    `api_trace_id` TEXT NULL COMMENT '接口请求链路ID',
    `api_request_id` TEXT NULL COMMENT '接口请求ID',
    `api_response_time` VARCHAR(64) NULL COMMENT '接口响应时间',
    `api_error_details` JSON NULL COMMENT '接口错误明细（JSON）',
    `api_total` BIGINT NULL COMMENT '接口返回总记录数',
    `api_start_date` VARCHAR(10) NULL COMMENT '接口返回的统计开始日期',
    `api_end_date` VARCHAR(10) NULL COMMENT '接口返回的统计结束日期',
    `api_day_interval` INT NULL COMMENT '接口返回的统计日期间隔天数',
    `api_amount_type` VARCHAR(32) NULL COMMENT '接口返回的计价类型：0成本计价，1固定值计价',
    `api_size` INT NULL COMMENT '接口返回的分页大小',
    `api_current` INT NULL COMMENT '接口返回的当前页码',
    `seller_id` TEXT NULL COMMENT '亚马逊店铺id',
    `sid` TEXT NULL COMMENT '店铺id',
    `wid` TEXT NULL COMMENT '系统仓库id',
    `ware_house_name` TEXT NULL COMMENT '仓库名称',
    `start_count` TEXT NULL COMMENT '期初库存-数量',
    `start_other_amount` TEXT NULL COMMENT '期初库存-商品成本 (精度：2位小数)',
    `start_logistic_amount` TEXT NULL COMMENT '期初库存-物流成本（精度：2位小数）',
    `shipments_count` TEXT NULL COMMENT '订单发货-数量',
    `shipments_other_amount` TEXT NULL COMMENT '订单发货-商品成本 (精度：2位小数)',
    `shipments_logistic_amount` TEXT NULL COMMENT '订单发货-物流成本 (精度：2位小数)',
    `whse_transfers_count` TEXT NULL COMMENT '库房转运-数量',
    `whse_transfers_other_amount` TEXT NULL COMMENT '库房转运-商品成本 (精度：2位小数)',
    `whse_transfers_logistic_amount` TEXT NULL COMMENT '库房转运-物流成本 (精度：2位小数)',
    `disposed_count` TEXT NULL COMMENT '弃置-数量',
    `disposed_other_amount` TEXT NULL COMMENT '弃置-商品成本 (精度：2位小数)',
    `disposed_logistic_amount` TEXT NULL COMMENT '弃置-物流成本 (精度：2位小数)',
    `found_count` TEXT NULL COMMENT '已找到-数量',
    `found_other_amount` TEXT NULL COMMENT '已找到-商品成本 (精度：2位小数)',
    `found_logistic_amount` TEXT NULL COMMENT '已找到-物流成本 (精度：2位小数)',
    `lost_count` TEXT NULL COMMENT '丢失-数量',
    `lost_other_amount` TEXT NULL COMMENT '丢失-商品成本 (精度：2位小数)',
    `lost_logistic_amount` TEXT NULL COMMENT '丢失-物流成本 (精度：2位小数)',
    `other_events_count` TEXT NULL COMMENT '其他-数量',
    `other_events_other_amount` TEXT NULL COMMENT '其他-商品成本 (精度：2位小数)',
    `other_events_logistic_amount` TEXT NULL COMMENT '其他-物流成本 (精度：2位小数)',
    `receipts_count` TEXT NULL COMMENT '货件补货-数量',
    `receipts_other_amount` TEXT NULL COMMENT '货件补货-商品成本 (精度：2位小数)',
    `receipts_logistic_amount` TEXT NULL COMMENT '货件补货-物流成本 (精度：2位小数)',
    `customer_returns_count` TEXT NULL COMMENT '买家退货-数量',
    `customer_returns_other_amount` TEXT NULL COMMENT '买家退货-商品成本 (精度：2位小数)',
    `customer_returns_logistic_amount` TEXT NULL COMMENT '买家退货-物流成本 (精度：2位小数)',
    `vendor_returns_count` TEXT NULL COMMENT '库存移除-数量',
    `vendor_returns_other_amount` TEXT NULL COMMENT '库存移除-商品成本 (精度：2位小数)',
    `vendor_returns_logistic_amount` TEXT NULL COMMENT '库存移除-物流成本 (精度：2位小数)',
    `difference_count` TEXT NULL COMMENT '库存差异-数量',
    `difference_other_amount` TEXT NULL COMMENT '库存差异-商品成本 (精度：2位小数)',
    `difference_logistic_amount` TEXT NULL COMMENT '库存差异-物流成本 (精度：2位小数)',
    `end_count` TEXT NULL COMMENT '期末库存-数量',
    `end_other_amount` TEXT NULL COMMENT '期末库存-商品成本 (精度：2位小数)',
    `end_logistic_amount` TEXT NULL COMMENT '期末库存-物流成本 (精度：2位小数)',
    `damaged_count` TEXT NULL COMMENT '残损-数量',
    `damaged_other_amount` TEXT NULL COMMENT '残损-商品成本 (精度：2位小数)',
    `damaged_logistic_amount` TEXT NULL COMMENT '残损-物流成本 (精度：2位小数)',
    `partition_index` TEXT NULL COMMENT '分区索引',
    `end_on_way_count` TEXT NULL COMMENT '期末在途-数量',
    `end_on_way_other_amount` TEXT NULL COMMENT '期末在途-商品成本 (精度：2位小数)',
    `end_on_way_logistic_amount` TEXT NULL COMMENT '期末在途-物流成本 (精度：2位小数)',
    `category_count` TEXT NULL COMMENT '商品种类',
    `parent_node` TEXT NULL COMMENT '是否父节点',
    `inventory_turnover_rate` TEXT NULL COMMENT '库存周转率 (精度：2位小数)',
    `inventory_turnover_days` TEXT NULL COMMENT '库存周转天数 (精度：2位小数)',
    `start_total_amount` TEXT NULL COMMENT '期初库存-总成本 (精度：2位小数)',
    `shipments_total_amount` TEXT NULL COMMENT '订单发货-总成本 (精度：2位小数)',
    `whse_transfers_total_amount` TEXT NULL COMMENT '库房转运-总成本 (精度：2位小数)',
    `disposed_total_amount` TEXT NULL COMMENT '弃置-总成本 (精度：2位小数)',
    `found_total_amount` TEXT NULL COMMENT '已找到-总成本 (精度：2位小数)',
    `lost_total_amount` TEXT NULL COMMENT '丢失-总成本 (精度：2位小数)',
    `other_events_total_amount` TEXT NULL COMMENT '其他-总成本 (精度：2位小数)',
    `receipts_total_amount` TEXT NULL COMMENT '货件补货-总成本 (精度：2位小数)',
    `customer_returns_total_amount` TEXT NULL COMMENT '订单退货-总成本 (精度：2位小数)',
    `vendor_returns_total_amount` TEXT NULL COMMENT '库存移除-总成本 (精度：2位小数)',
    `difference_total_amount` TEXT NULL COMMENT '库存差异-总成本 (精度：2位小数)',
    `end_total_amount` TEXT NULL COMMENT '期末库存-总成本 (精度：2位小数)',
    `damaged_total_amount` TEXT NULL COMMENT '已残损-总成本 (精度：2位小数)',
    `end_on_way_total_amount` TEXT NULL COMMENT '期末在途-总成本 (精度：2位小数)',
    `stock_to_use_rate` TEXT NULL COMMENT '存销比 (精度：2位小数)',
    `adjustments_count` TEXT NULL COMMENT '成本调整-数量',
    `adjustments_total_amount` TEXT NULL COMMENT '成本调整-总成本 (精度：2位小数)',
    `adjustments_logistic_amount` TEXT NULL COMMENT '成本调整-物流成本 (精度：2位小数)',
    `adjustments_other_amount` TEXT NULL COMMENT '成本调整-商品成本 (精度：2位小数)',
    `transferring_out_count` TEXT NULL COMMENT '移仓在途-数量',
    `transferring_out_total_amount` TEXT NULL COMMENT '移仓在途-总成本 (精度：2位小数)',
    `transferring_out_logistic_amount` TEXT NULL COMMENT '移仓在途-物流成本 (精度：2位小数)',
    `transferring_out_other_amount` TEXT NULL COMMENT '移仓在途-商品成本 (精度：2位小数)',
    `mid` TEXT NULL COMMENT '站点id',
    `parent_asin` TEXT NULL COMMENT '父Asin',
    `msku` TEXT NULL COMMENT '亚马逊卖家SKU（MSKU）',
    `asin` TEXT NULL COMMENT '亚马逊商品标识码（ASIN）',
    `disposition` TEXT NULL COMMENT '库存属性： sellable 可售 unsellable 不可售 all 全部',
    `country_code` TEXT NULL COMMENT '国家编码',
    `fnsku` TEXT NULL COMMENT '亚马逊配送网络SKU（FNSKU）',
    `product_id` TEXT NULL COMMENT '本地产品id',
    `local_sku` TEXT NULL COMMENT '本地产品sku',
    `local_name` TEXT NULL COMMENT '本地产品名称',
    `cid` TEXT NULL COMMENT '商品分类id',
    `product_category_name` TEXT NULL COMMENT '产品分类名',
    `bid` TEXT NULL COMMENT '品牌id',
    `brand_name` TEXT NULL COMMENT '品牌名称',
    `valuation_method` TEXT NULL COMMENT '计价方法： 1 先进先出 2 移动加权 3 月末加权',
    `child_data` JSON NULL COMMENT '返回字段与上级row_data一致',
    `raw_row_json` JSON NOT NULL COMMENT '接口返回的完整原始明细行（JSON），兼容新增字段',
    `pulled_at` DATETIME NOT NULL COMMENT '数据拉取时间',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    PRIMARY KEY (`id`),
    KEY `idx_stat_month` (`stat_month`),
    KEY `idx_sync_batch` (`sync_batch_id`),
    KEY `idx_fba_identity` (`stat_month`,`sid`(32),`wid`(32),`msku`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='ODS-领星FBA月度库存报表明细原始数据';

CREATE TABLE IF NOT EXISTS `ods_lingxing_overseas_monthly_inventory_detail` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `stat_month` CHAR(7) NOT NULL COMMENT '数据归属年月，格式YYYY-MM',
    `sync_batch_id` VARCHAR(64) NOT NULL COMMENT '本次同步批次ID',
    `query_start_date` VARCHAR(10) NOT NULL COMMENT '本次接口查询开始日期',
    `query_end_date` VARCHAR(10) NOT NULL COMMENT '本次接口查询结束日期',
    `request_scope_json` JSON NOT NULL COMMENT '本次请求的sys_wid仓库范围（JSON）',
    `source_page` INT NOT NULL DEFAULT 1 COMMENT '接口来源页码',
    `source_offset` INT NOT NULL DEFAULT 0 COMMENT '接口来源偏移量',
    `source_row_no` INT NOT NULL DEFAULT 0 COMMENT '同步批次内原始行号',
    `api_code` VARCHAR(32) NULL COMMENT '接口返回状态码',
    `api_message` TEXT NULL COMMENT '接口返回提示信息',
    `api_trace_id` TEXT NULL COMMENT '接口请求链路ID',
    `api_request_id` TEXT NULL COMMENT '接口请求ID',
    `api_response_time` VARCHAR(64) NULL COMMENT '接口响应时间',
    `api_error_details` JSON NULL COMMENT '接口错误明细（JSON）',
    `api_total` BIGINT NULL COMMENT '接口返回总记录数',
    `api_start_date` VARCHAR(10) NULL COMMENT '接口返回的统计开始日期',
    `api_end_date` VARCHAR(10) NULL COMMENT '接口返回的统计结束日期',
    `api_day_interval` INT NULL COMMENT '接口返回的统计日期间隔天数',
    `api_amount_type` VARCHAR(32) NULL COMMENT '接口返回的计价类型：0成本计价，1固定值计价',
    `api_size` INT NULL COMMENT '接口返回的分页大小',
    `api_current` INT NULL COMMENT '接口返回的当前页码',
    `sys_wid` TEXT NULL COMMENT '仓库id',
    `ware_house_name` TEXT NULL COMMENT '仓库名称',
    `seller_name` TEXT NULL COMMENT '店铺名称',
    `product_name` TEXT NULL COMMENT '商品名称',
    `product_type` TEXT NULL COMMENT '产品类型:普通产品 组合产品 辅料 捆绑产品',
    `sku` TEXT NULL COMMENT '商品SKU',
    `fnsku` TEXT NULL COMMENT '亚马逊配送网络SKU（FNSKU）',
    `spu` TEXT NULL COMMENT '标准产品单元（SPU）',
    `spu_name` TEXT NULL COMMENT '款名',
    `api_sku` TEXT NULL COMMENT '第三方SKU',
    `brand` TEXT NULL COMMENT '品牌名称',
    `category1` TEXT NULL COMMENT '一级类目-名称',
    `category2` TEXT NULL COMMENT '二级类目-名称',
    `category3` TEXT NULL COMMENT '三级类目-名称',
    `attribute_text` TEXT NULL COMMENT '库存属性: 全部 可售 待检 不可售',
    `global_tags` JSON NULL COMMENT '产品标签列表',
    `sku_attribute` JSON NULL COMMENT '产品属性',
    `allocation_in_cost` TEXT NULL COMMENT '调拨入库-成本（精度：2位小数点）',
    `allocation_in_count` TEXT NULL COMMENT '调拨入库-数量',
    `allocation_in_transit_cost` TEXT NULL COMMENT '期末在途-成本（精度：2位小数点）',
    `allocation_in_transit_count` TEXT NULL COMMENT '期末在途-数量',
    `allocation_out_cost` TEXT NULL COMMENT '调拨出库-成本（精度：2位小数点）',
    `allocation_out_count` TEXT NULL COMMENT '调拨出库-数量',
    `change_of_standard_in_cost` TEXT NULL COMMENT '换标入库-成本（精度：2位小数点）',
    `change_of_standard_in_count` TEXT NULL COMMENT '换标入库-数量',
    `change_of_standard_out_cost` TEXT NULL COMMENT '换标出库-成本（精度：2位小数点）',
    `change_of_standard_out_count` TEXT NULL COMMENT '换标出库-数量',
    `cost_adjustment` TEXT NULL COMMENT '成本调整（精度：2位小数点）',
    `day_early_cost` TEXT NULL COMMENT '期初库存-成本（精度：2位小数点）',
    `day_early_count` TEXT NULL COMMENT '期初库存-数量',
    `day_end_cost` TEXT NULL COMMENT '期末库存-成本（精度：2位小数点）',
    `day_end_count` TEXT NULL COMMENT '期末库存-数量',
    `fba_out_cost` TEXT NULL COMMENT 'fba出库-成本（精度：2位小数点）',
    `fba_out_count` TEXT NULL COMMENT 'fba出库-数量',
    `fbm_out_cost` TEXT NULL COMMENT 'fbm出库-成本（精度：2位小数点）',
    `fbm_out_count` TEXT NULL COMMENT 'fbm出库-数量',
    `inventory_deficit_out_cost` TEXT NULL COMMENT '盘亏出库-成本（精度：2位小数点）',
    `inventory_deficit_out_count` TEXT NULL COMMENT '盘亏出库-数量',
    `inventory_surplus_in_cost` TEXT NULL COMMENT '盘盈入库-成本（精度：2位小数点）',
    `inventory_surplus_in_count` TEXT NULL COMMENT '盘盈入库-数量',
    `other_in_cost` TEXT NULL COMMENT '其他入库-成本（精度：2位小数点）',
    `other_in_count` TEXT NULL COMMENT '其他入库-数量',
    `other_out_cost` TEXT NULL COMMENT '其他出库-成本（精度：2位小数点）',
    `other_out_count` TEXT NULL COMMENT '其他出库-数量',
    `outsourcing_in_cost` TEXT NULL COMMENT '委外入库-成本（精度：2位小数点）',
    `outsourcing_in_count` TEXT NULL COMMENT '委外入库-数量',
    `outsourcing_out_cost` TEXT NULL COMMENT '委外出库-成本（精度：2位小数点）',
    `outsourcing_out_count` TEXT NULL COMMENT '委外出库-数量',
    `processing_in_cost` TEXT NULL COMMENT '加工入库-成本（精度：2位小数点）',
    `processing_in_count` TEXT NULL COMMENT '加工入库-数量',
    `processing_out_cost` TEXT NULL COMMENT '加工出库-成本（精度：2位小数点）',
    `processing_out_count` TEXT NULL COMMENT '加工出库-数量',
    `purchase_in_cost` TEXT NULL COMMENT '采购入库-成本（精度：2位小数点）',
    `purchase_in_count` TEXT NULL COMMENT '采购入库-数量',
    `purchase_return_cost` TEXT NULL COMMENT '退货出库-成本（精度：2位小数点）',
    `purchase_return_count` TEXT NULL COMMENT '退货出库-数量',
    `remove_in_cost` TEXT NULL COMMENT '移除入库-成本（精度：2位小数点）',
    `remove_in_count` TEXT NULL COMMENT '移除入库-数量',
    `return_goods_in_cost` TEXT NULL COMMENT '退货入库-成本（精度：2位小数点）',
    `return_goods_in_count` TEXT NULL COMMENT '退货入库-数量',
    `split_in_cost` TEXT NULL COMMENT '拆分入库-成本（精度：2位小数点）',
    `split_in_count` TEXT NULL COMMENT '拆分入库-数量',
    `split_out_cost` TEXT NULL COMMENT '拆分出库-成本（精度：2位小数点）',
    `split_out_count` TEXT NULL COMMENT '拆分出库-数量',
    `wfs_out_cost` TEXT NULL COMMENT 'WFS出库-成本（精度：2位小数点）',
    `wfs_out_count` TEXT NULL COMMENT 'WFS出库-数量',
    `gifts_in_cost` TEXT NULL COMMENT '赠品入库-成本(精度：2位小数点)',
    `gifts_in_count` TEXT NULL COMMENT '赠品入库-数量',
    `rotation_day_cost` TEXT NULL COMMENT '周转天数-成本（精度：2位小数点）',
    `rotation_day_count` TEXT NULL COMMENT '周转天数-数量（精度：2位小数点）',
    `rotation_rate_count` TEXT NULL COMMENT '周转率-数量（精度：4位小数点）',
    `rotation_rate_cost` TEXT NULL COMMENT '周转率-成本（精度：4位小数点）',
    `sales_ratio_count` TEXT NULL COMMENT '存销比-数量（精度：4位小数点）',
    `sales_ratio_cost` TEXT NULL COMMENT '存销比-成本（精度：4位小数点）',
    `api_day_early_count` TEXT NULL COMMENT '第三方期初库存-数量',
    `api_day_end_count` TEXT NULL COMMENT '第三方期末库存-数量',
    `divergence_count` TEXT NULL COMMENT '库存差异（第三方期末库存 - 期末库存）',
    `child_list` JSON NULL COMMENT '子项，与外层列表字段一致-库存状态为全部时会有数据',
    `raw_row_json` JSON NOT NULL COMMENT '接口返回的完整原始明细行（JSON），兼容新增字段',
    `pulled_at` DATETIME NOT NULL COMMENT '数据拉取时间',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    PRIMARY KEY (`id`),
    KEY `idx_stat_month` (`stat_month`),
    KEY `idx_sync_batch` (`sync_batch_id`),
    KEY `idx_overseas_identity` (`stat_month`,`sys_wid`(32),`sku`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='ODS-领星海外仓月度库存报表明细原始数据';

CREATE TABLE IF NOT EXISTS `ods_lingxing_local_monthly_inventory_detail` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `stat_month` CHAR(7) NOT NULL COMMENT '数据归属年月，格式YYYY-MM',
    `sync_batch_id` VARCHAR(64) NOT NULL COMMENT '本次同步批次ID',
    `query_start_date` VARCHAR(10) NOT NULL COMMENT '本次接口查询开始日期',
    `query_end_date` VARCHAR(10) NOT NULL COMMENT '本次接口查询结束日期',
    `request_scope_json` JSON NOT NULL COMMENT '本次请求的sys_wid仓库范围（JSON）',
    `source_page` INT NOT NULL DEFAULT 1 COMMENT '接口来源页码',
    `source_offset` INT NOT NULL DEFAULT 0 COMMENT '接口来源偏移量',
    `source_row_no` INT NOT NULL DEFAULT 0 COMMENT '同步批次内原始行号',
    `api_code` VARCHAR(32) NULL COMMENT '接口返回状态码',
    `api_message` TEXT NULL COMMENT '接口返回提示信息',
    `api_trace_id` TEXT NULL COMMENT '接口请求链路ID',
    `api_request_id` TEXT NULL COMMENT '接口请求ID',
    `api_response_time` VARCHAR(64) NULL COMMENT '接口响应时间',
    `api_error_details` JSON NULL COMMENT '接口错误明细（JSON）',
    `api_total` BIGINT NULL COMMENT '接口返回总记录数',
    `api_start_date` VARCHAR(10) NULL COMMENT '接口返回的统计开始日期',
    `api_end_date` VARCHAR(10) NULL COMMENT '接口返回的统计结束日期',
    `api_day_interval` INT NULL COMMENT '接口返回的统计日期间隔天数',
    `api_amount_type` VARCHAR(32) NULL COMMENT '接口返回的计价类型：0成本计价，1固定值计价',
    `api_size` INT NULL COMMENT '接口返回的分页大小',
    `api_current` INT NULL COMMENT '接口返回的当前页码',
    `sys_wid` TEXT NULL COMMENT '系统仓库ID',
    `ware_house_name` TEXT NULL COMMENT '仓库名称',
    `seller_name` TEXT NULL COMMENT '店铺名称',
    `product_name` TEXT NULL COMMENT '商品名称',
    `product_type` TEXT NULL COMMENT '产品类型:普通产品 组合产品 辅料 捆绑产品',
    `sku` TEXT NULL COMMENT '商品SKU',
    `fnsku` TEXT NULL COMMENT '亚马逊配送网络SKU（FNSKU）',
    `spu` TEXT NULL COMMENT '标准产品单元（SPU）',
    `spu_name` TEXT NULL COMMENT '款名',
    `brand` TEXT NULL COMMENT '品牌名称',
    `category1` TEXT NULL COMMENT '一级类目-名称',
    `category2` TEXT NULL COMMENT '二级类目-名称',
    `category3` TEXT NULL COMMENT '三级类目-名称',
    `attribute_text` TEXT NULL COMMENT '库存属性: 全部 可售 待检 不可售',
    `global_tags` JSON NULL COMMENT '产品标签列表',
    `sku_attribute` JSON NULL COMMENT '产品属性',
    `allocation_in_cost` TEXT NULL COMMENT '调拨入库-成本（精度：2位小数点）',
    `allocation_in_count` TEXT NULL COMMENT '调拨入库-数量',
    `allocation_in_transit_cost` TEXT NULL COMMENT '期末在途-成本（精度：2位小数点）',
    `allocation_in_transit_count` TEXT NULL COMMENT '期末在途-数量',
    `allocation_out_cost` TEXT NULL COMMENT '调拨出库-成本（精度：2位小数点）',
    `allocation_out_count` TEXT NULL COMMENT '调拨出库-数量',
    `change_of_standard_in_cost` TEXT NULL COMMENT '换标入库-成本（精度：2位小数点）',
    `change_of_standard_in_count` TEXT NULL COMMENT '换标入库-数量',
    `change_of_standard_out_cost` TEXT NULL COMMENT '换标出库-成本（精度：2位小数点）',
    `change_of_standard_out_count` TEXT NULL COMMENT '换标出库-数量',
    `cost_adjustment` TEXT NULL COMMENT '成本调整（精度：2位小数点）',
    `day_early_cost` TEXT NULL COMMENT '期初库存-成本（精度：2位小数点）',
    `day_early_count` TEXT NULL COMMENT '期初库存-数量',
    `day_end_cost` TEXT NULL COMMENT '期末库存-成本（精度：2位小数点）',
    `day_end_count` TEXT NULL COMMENT '期末库存-数量',
    `fba_out_cost` TEXT NULL COMMENT 'fba出库-成本（精度：2位小数点）',
    `fba_out_count` TEXT NULL COMMENT 'fba出库-数量',
    `fbm_out_cost` TEXT NULL COMMENT 'fbm出库-成本（精度：2位小数点）',
    `fbm_out_count` TEXT NULL COMMENT 'fbm出库-数量',
    `inventory_deficit_out_cost` TEXT NULL COMMENT '盘亏出库-成本（精度：2位小数点）',
    `inventory_deficit_out_count` TEXT NULL COMMENT '盘亏出库-数量',
    `inventory_surplus_in_cost` TEXT NULL COMMENT '盘盈入库-成本（精度：2位小数点）',
    `inventory_surplus_in_count` TEXT NULL COMMENT '盘盈入库-数量',
    `other_in_cost` TEXT NULL COMMENT '其他入库-成本（精度：2位小数点）',
    `other_in_count` TEXT NULL COMMENT '其他入库-数量',
    `other_out_cost` TEXT NULL COMMENT '其他出库-成本（精度：2位小数点）',
    `other_out_count` TEXT NULL COMMENT '其他出库-数量',
    `outsourcing_in_cost` TEXT NULL COMMENT '委外入库-成本（精度：2位小数点）',
    `outsourcing_in_count` TEXT NULL COMMENT '委外入库-数量',
    `outsourcing_out_cost` TEXT NULL COMMENT '委外出库-成本（精度：2位小数点）',
    `outsourcing_out_count` TEXT NULL COMMENT '委外出库-数量',
    `processing_in_cost` TEXT NULL COMMENT '加工入库-成本（精度：2位小数点）',
    `processing_in_count` TEXT NULL COMMENT '加工入库-数量',
    `processing_out_cost` TEXT NULL COMMENT '加工出库-成本（精度：2位小数点）',
    `processing_out_count` TEXT NULL COMMENT '加工出库-数量',
    `purchase_in_cost` TEXT NULL COMMENT '采购入库-成本（精度：2位小数点）',
    `purchase_in_count` TEXT NULL COMMENT '采购入库-数量',
    `purchase_return_cost` TEXT NULL COMMENT '退货出库-成本（精度：2位小数点）',
    `purchase_return_count` TEXT NULL COMMENT '退货出库-数量',
    `remove_in_cost` TEXT NULL COMMENT '移除入库-成本（精度：2位小数点）',
    `remove_in_count` TEXT NULL COMMENT '移除入库-数量',
    `return_goods_in_cost` TEXT NULL COMMENT '退货入库-成本（精度：2位小数点）',
    `return_goods_in_count` TEXT NULL COMMENT '退货入库-数量',
    `rotation_day_cost` TEXT NULL COMMENT '周转天数-成本（精度：2位小数点）',
    `rotation_day_count` TEXT NULL COMMENT '周转天数-数量（精度：2位小数点）',
    `split_in_cost` TEXT NULL COMMENT '拆分入库-成本（精度：2位小数点）',
    `split_in_count` TEXT NULL COMMENT '拆分入库-数量',
    `split_out_cost` TEXT NULL COMMENT '拆分出库-成本（精度：2位小数点）',
    `split_out_count` TEXT NULL COMMENT '拆分出库-数量',
    `wfs_out_cost` TEXT NULL COMMENT 'WFS出库-成本（精度：2位小数点）',
    `wfs_out_count` TEXT NULL COMMENT 'WFS出库-数量',
    `gifts_in_cost` TEXT NULL COMMENT '赠品入库-成本（精度：2位小数点）',
    `gifts_in_count` TEXT NULL COMMENT '赠品入库-数量',
    `rotation_rate_count` TEXT NULL COMMENT '周转率-数量（精度：4位小数点）',
    `rotation_rate_cost` TEXT NULL COMMENT '周转率-成本（精度：4位小数点）',
    `sales_ratio_count` TEXT NULL COMMENT '存销比-数量（精度：4位小数点）',
    `sales_ratio_cost` TEXT NULL COMMENT '存销比-成本（精度：4位小数点）',
    `child_list` JSON NULL COMMENT '子项，与外层列表字段一致-库存状态为全部时会有数据',
    `raw_row_json` JSON NOT NULL COMMENT '接口返回的完整原始明细行（JSON），兼容新增字段',
    `pulled_at` DATETIME NOT NULL COMMENT '数据拉取时间',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    PRIMARY KEY (`id`),
    KEY `idx_stat_month` (`stat_month`),
    KEY `idx_sync_batch` (`sync_batch_id`),
    KEY `idx_local_identity` (`stat_month`,`sys_wid`(32),`sku`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='ODS-领星本地仓月度库存报表明细原始数据';

CREATE TABLE IF NOT EXISTS `ods_lingxing_inventory_report_amz_order_profit` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `stat_month` CHAR(7) NOT NULL COMMENT '数据归属年月，格式YYYY-MM',
    `sid` VARCHAR(32) NOT NULL COMMENT '领星Amazon店铺SID',
    `msku` VARCHAR(255) NOT NULL COMMENT 'Amazon卖家SKU（MSKU）',
    `local_sku` VARCHAR(255) NULL COMMENT '本地商品SKU',
    `asin` VARCHAR(64) NULL COMMENT 'Amazon商品标识码（ASIN）',
    `item_name` TEXT NULL COMMENT '商品名称',
    `currency_code` VARCHAR(16) NOT NULL DEFAULT 'CNY' COMMENT '销售额币种，本链路固定请求CNY',
    `amount` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '上个自然月销售额',
    `volume` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '自然月商品销量',
    `pulled_at` DATETIME NOT NULL COMMENT '数据拉取时间',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_inventory_amz_profit_month_sid_msku` (`stat_month`,`sid`,`msku`),
    KEY `idx_inventory_amz_profit_month_local_sku` (`stat_month`,`local_sku`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='ODS-月度库存统计使用的领星Amazon订单利润最小字段快照';

CREATE TABLE IF NOT EXISTS `ods_inventory_report_ebay_sales` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `stat_month` CHAR(7) NOT NULL COMMENT '数据归属年月，格式YYYY-MM，由上传时选择',
    `sku` VARCHAR(255) NOT NULL COMMENT 'eBay商品SKU',
    `brand_code` VARCHAR(32) NOT NULL COMMENT '从SKU解析出的品牌编码',
    `image_url` TEXT NULL COMMENT '商品图片链接',
    `multi_variant` VARCHAR(16) NULL COMMENT '是否多属性',
    `product_sales_amount` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '商品销售额',
    `receivable_shipping_amount` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '应收运费',
    `amount` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '实际达成金额，商品销售额加应收运费',
    `source_file_name` VARCHAR(255) NOT NULL COMMENT '上传源文件名',
    `source_sheet` VARCHAR(128) NOT NULL COMMENT '上传源工作表名',
    `source_row` INT NOT NULL COMMENT '上传源文件行号',
    `import_batch_id` VARCHAR(64) NOT NULL COMMENT '上传批次ID，用于数据追溯',
    `imported_by` VARCHAR(64) NULL COMMENT '上传人账号',
    `imported_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据导入时间',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    PRIMARY KEY (`id`),
    KEY `idx_inventory_ebay_sales_month_sku` (`stat_month`,`sku`),
    KEY `idx_inventory_ebay_sales_month_brand` (`stat_month`,`brand_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='ODS-月度库存统计eBay SKU销售额上传源数据';

INSERT INTO `scheduler_task` (
    task_code, task_name, cron_expression, enabled, description
) VALUES (
    'monthly_inventory_report_source_sync',
    '月度库存统计表数据拉取',
    '0 0 6 1 * ?',
    1,
    'FBA、海外仓、本地仓和Amazon订单利润四个接口均拉取上个完整自然月并按月份覆盖ODS；订单利润固定CNY，仅保存商品标识和销售额；随后重建库存DWD明细、实际达成和DWS汇总'
)
ON DUPLICATE KEY UPDATE
    task_name = VALUES(task_name),
    cron_expression = VALUES(cron_expression),
    description = VALUES(description);
