CREATE TABLE IF NOT EXISTS ebay_sku_analysis_import_batch (
  import_batch_id VARCHAR(64) NOT NULL COMMENT '导入批次ID', source_file_name VARCHAR(255) NOT NULL COMMENT '来源文件名',
  imported_months VARCHAR(255) NOT NULL COMMENT '本次覆盖月份列表', total_rows INT NOT NULL DEFAULT 0 COMMENT 'Excel总行数',
  valid_rows INT NOT NULL DEFAULT 0 COMMENT '有效入库行数', skipped_rows INT NOT NULL DEFAULT 0 COMMENT '跳过行数',
  operator_name VARCHAR(128) DEFAULT NULL COMMENT '上传操作人', status VARCHAR(32) NOT NULL COMMENT '导入状态',
  error_message VARCHAR(1000) DEFAULT NULL COMMENT '失败原因', create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  complete_time DATETIME DEFAULT NULL COMMENT '完成时间', PRIMARY KEY (import_batch_id), KEY idx_esa_batch_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='eBay SKU分析文件导入批次';
CREATE TABLE IF NOT EXISTS ods_ebay_sku_analysis_order_raw (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  import_batch_id VARCHAR(64) NOT NULL COMMENT '导入批次ID',
  stat_month CHAR(7) NOT NULL COMMENT '统计月份，格式YYYY-MM',
  source_file_name VARCHAR(255) NOT NULL COMMENT '来源文件名',
  source_sheet VARCHAR(128) NOT NULL COMMENT '来源工作表',
  source_row INT NOT NULL COMMENT '来源Excel行号',
  source_site_name VARCHAR(100) DEFAULT NULL COMMENT 'Excel第一列原始站点',
  platform_order_no VARCHAR(128) NOT NULL COMMENT '平台订单号',
  shipping_status VARCHAR(64) DEFAULT NULL COMMENT '发货状态',
  order_time DATETIME DEFAULT NULL COMMENT '下单时间',
  payment_time DATETIME NOT NULL COMMENT '付款时间',
  refund_time DATETIME DEFAULT NULL COMMENT '退款时间',
  currency_code VARCHAR(16) DEFAULT NULL COMMENT '币种',
  goods_receivable_original DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '应收货款（订单级别，原币）',
  goods_receivable_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '应收货款（订单级别，人民币）',
  shipping_receivable_original DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '应收运费（原币）',
  shipping_receivable_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '应收运费（人民币）',
  tax_usd DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '税费（美元）',
  tax_usd_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '税费（美元字段换算人民币）',
  platform_fee_original DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '平台费用（原币）',
  platform_product_unit_price DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '平台产品单价',
  platform_product_unit_price_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '平台产品单价（人民币）',
  product_unit_price DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '产品单价',
  product_unit_price_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '产品单价（人民币）',
  source_refund_amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT 'Excel退款金额原始值',
  source_refund_amount_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '退款金额（人民币）',
  tax_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '税费（人民币）',
  advertising_fee_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '广告费（人民币）',
  last_mile_shipping_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '实际尾程运费（人民币）',
  platform_fee_detail TEXT DEFAULT NULL COMMENT '平台费用明细',
  first_mile_shipping_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '头程运费（人民币）',
  purchase_cost_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '采购成本（人民币）',
  exchange_rate DECIMAL(20,8) NOT NULL DEFAULT 0 COMMENT '汇率',
  customer_id VARCHAR(255) DEFAULT NULL COMMENT '客户ID',
  picture_url TEXT DEFAULT NULL COMMENT '图片链接',
  product_name_cn VARCHAR(500) DEFAULT NULL COMMENT '产品名称（中文）',
  platform_sku VARCHAR(128) DEFAULT NULL COMMENT '平台SKU',
  inventory_sku VARCHAR(128) NOT NULL COMMENT '库存SKU',
  sku_status VARCHAR(64) DEFAULT NULL COMMENT 'SKU状态',
  listing_url TEXT DEFAULT NULL COMMENT 'Listing链接',
  available_inventory DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '可用库存',
  order_profit_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '订单利润（人民币）',
  order_total_amount_original DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '订单总金额（原币）',
  purchase_quantity DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '购买数量',
  platform_sku_quantity DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '平台SKU数量',
  order_remark TEXT DEFAULT NULL COMMENT '订单备注',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id),
  KEY idx_esa_raw_month (stat_month), KEY idx_esa_raw_sku (inventory_sku), KEY idx_esa_raw_order_date (platform_order_no,payment_time), KEY idx_esa_raw_batch (import_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ODS-eBay SKU分析订单上传结构化源数据';
CREATE TABLE IF NOT EXISTS dwd_ebay_sku_analysis_order (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID', stat_month CHAR(7) NOT NULL COMMENT '统计月份，格式YYYY-MM', payment_time DATETIME NOT NULL COMMENT '付款时间', refund_time DATETIME DEFAULT NULL COMMENT '退款时间',
  platform_order_no VARCHAR(128) NOT NULL COMMENT '平台订单号', inventory_sku VARCHAR(128) NOT NULL COMMENT '标准库存SKU', purchase_quantity DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '购买数量',
  paid_amount_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '已支付金额人民币', shipping_amount_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '运费人民币',
  platform_fee_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '平台费用人民币', paid_amount_original DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '应收货款加应收运费原币（按订单SKU分摊）', shipping_amount_original DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '应收运费原币', refund_quantity DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '退货数量，状态包含已退款或已作废', refund_amount_original DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '退款金额原币（按退款行分摊）', refund_amount_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '退款金额人民币', shipping_status VARCHAR(64) DEFAULT NULL COMMENT '发货状态', currency_code VARCHAR(16) DEFAULT NULL COMMENT '币种', customer_id VARCHAR(255) DEFAULT NULL COMMENT '客户ID', site_code VARCHAR(32) NOT NULL COMMENT '标准站点代码', site_name VARCHAR(100) NOT NULL DEFAULT '其他' COMMENT '中文站点名称',
  country_name VARCHAR(128) DEFAULT NULL COMMENT '国家名称',
  picture_url TEXT DEFAULT NULL COMMENT '图片链接，取上传源数据',
  product_name_cn VARCHAR(500) DEFAULT NULL COMMENT '产品名称（中文），取上传源数据',
  listing_url TEXT DEFAULT NULL COMMENT 'Listing链接，取上传源数据',
  order_remark TEXT DEFAULT NULL COMMENT '原始订单备注，作为退款原因展示',
  import_batch_id VARCHAR(64) NOT NULL COMMENT '导入批次ID',
  source_row INT NOT NULL COMMENT '来源Excel行号', create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', PRIMARY KEY (id),
  UNIQUE KEY uk_esa_dwd_month_row (stat_month, import_batch_id, source_row), KEY idx_esa_dwd_order_date (platform_order_no,payment_time), KEY idx_esa_dwd_time (payment_time), KEY idx_esa_dwd_sku (inventory_sku), KEY idx_esa_dwd_site (site_code), KEY idx_esa_dwd_site_sku_time (site_name,inventory_sku,payment_time), KEY idx_esa_dwd_return_time (refund_time,site_name,inventory_sku)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DWD-eBay SKU分析订单清洗明细';

CREATE TABLE IF NOT EXISTS ebay_sku_analysis_return_classification (
  platform_order_no VARCHAR(128) NOT NULL COMMENT 'eBay平台订单号，分类持久化唯一键',
  category_id BIGINT UNSIGNED NOT NULL COMMENT '售后分类维表ID',
  responsible_party VARCHAR(100) DEFAULT NULL COMMENT '负责方快照',
  big_category VARCHAR(50) NOT NULL COMMENT '售后大类快照',
  small_category VARCHAR(100) NOT NULL COMMENT '售后小类快照',
  classification_description TEXT DEFAULT NULL COMMENT '分类说明快照',
  classified_by VARCHAR(128) DEFAULT NULL COMMENT '最后分类操作人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '首次分类时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  PRIMARY KEY (platform_order_no),
  KEY idx_esa_return_category (category_id,big_category,small_category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='eBay退货订单人工售后分类映射';

CREATE TABLE IF NOT EXISTS ebay_sku_analysis_profit_import_batch (
  import_batch_id VARCHAR(64) NOT NULL COMMENT '利润表导入批次ID',
  source_file_name VARCHAR(255) NOT NULL COMMENT '来源文件名',
  imported_months VARCHAR(255) NOT NULL COMMENT '本次导入包含月份列表',
  total_rows INT NOT NULL DEFAULT 0 COMMENT 'Excel总行数',
  valid_rows INT NOT NULL DEFAULT 0 COMMENT '有效eBay利润行数',
  skipped_rows INT NOT NULL DEFAULT 0 COMMENT '跳过行数',
  excluded_walmart_rows INT NOT NULL DEFAULT 0 COMMENT '排除的Walmart行数',
  excluded_amz_rows INT NOT NULL DEFAULT 0 COMMENT '排除的含AMZ字样SKU行数',
  operator_name VARCHAR(128) DEFAULT NULL COMMENT '上传操作人',
  status VARCHAR(32) NOT NULL COMMENT '导入状态',
  error_message VARCHAR(1000) DEFAULT NULL COMMENT '失败原因',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  complete_time DATETIME DEFAULT NULL COMMENT '完成时间',
  PRIMARY KEY (import_batch_id),
  KEY idx_esa_profit_batch_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='eBay SKU分析订单利润表导入批次';

CREATE TABLE IF NOT EXISTS ods_ebay_sku_analysis_profit_raw (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  import_batch_id VARCHAR(64) NOT NULL COMMENT '利润表导入批次ID',
  stat_month CHAR(7) NOT NULL COMMENT '付款月份，格式YYYY-MM',
  source_file_name VARCHAR(255) NOT NULL COMMENT '来源文件名',
  source_sheet VARCHAR(128) NOT NULL COMMENT '来源工作表',
  source_row INT NOT NULL COMMENT '来源Excel行号',
  account_name VARCHAR(255) DEFAULT NULL COMMENT '账号',
  source_site_name VARCHAR(100) NOT NULL COMMENT 'Excel原始站点',
  site_name VARCHAR(100) NOT NULL COMMENT '标准站点名称',
  platform_order_no VARCHAR(128) NOT NULL COMMENT '订单号',
  listing_id VARCHAR(128) DEFAULT NULL COMMENT 'Listing ID',
  picture_url TEXT DEFAULT NULL COMMENT '图片链接',
  source_sku VARCHAR(128) DEFAULT NULL COMMENT 'Excel的SKU字段',
  platform_sku VARCHAR(128) DEFAULT NULL COMMENT '平台SKU，空值时由库存SKU补齐',
  inventory_sku VARCHAR(128) NOT NULL COMMENT '标准库存SKU，优先库存SKU并回退平台SKU',
  quantity DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '数量',
  unit_price_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '单价人民币',
  product_name VARCHAR(500) DEFAULT NULL COMMENT '产品名称',
  product_name_secondary VARCHAR(500) DEFAULT NULL COMMENT '产品名称备用字段',
  cost_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '成本人民币',
  order_amount_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '订单金额人民币',
  sold_quantity DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '售出数',
  order_count DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '订单数',
  tax_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '税费人民币',
  order_time DATETIME DEFAULT NULL COMMENT '下单时间',
  payment_time DATETIME NOT NULL COMMENT '付款时间',
  refund_time DATETIME DEFAULT NULL COMMENT '退款时间',
  order_status VARCHAR(128) DEFAULT NULL COMMENT '订单状态',
  financial_status VARCHAR(128) DEFAULT NULL COMMENT '财务状态',
  profit_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '利润人民币',
  source_profit_rate DECIMAL(20,8) NOT NULL DEFAULT 0 COMMENT 'Excel原始利润率',
  product_sales_amount_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '商品销售额人民币',
  shipping_receivable_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '应收运费人民币',
  platform_fee_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '平台费用人民币',
  purchase_cost_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '采购成本人民币',
  first_mile_shipping_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '头程运费人民币',
  customs_tax_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '海关税费人民币',
  last_mile_shipping_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '尾程运费人民币',
  refund_amount_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '退款金额人民币',
  advertising_fee_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '广告费人民币',
  other_platform_fee_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '平台其他费人民币',
  refund_amount_by_order_time_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '按下单时间统计退款金额人民币',
  manual_purchase_cost_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '手工采购成本人民币',
  first_mile_cost_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '头程成本人民币',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id),
  KEY idx_esa_profit_raw_month (stat_month),
  KEY idx_esa_profit_raw_match (platform_order_no,payment_time,inventory_sku),
  KEY idx_esa_profit_raw_sku_site (inventory_sku,site_name),
  KEY idx_esa_profit_raw_batch (import_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ODS-eBay SKU分析订单利润结构化源数据';

CREATE TABLE IF NOT EXISTS dwd_ebay_sku_analysis_profit (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  stat_month CHAR(7) NOT NULL COMMENT '付款月份，格式YYYY-MM',
  payment_date DATE NOT NULL COMMENT '付款日期',
  payment_time DATETIME NOT NULL COMMENT '付款时间',
  platform_order_no VARCHAR(128) NOT NULL COMMENT '订单号',
  inventory_sku VARCHAR(128) NOT NULL COMMENT '标准库存SKU',
  platform_sku VARCHAR(128) DEFAULT NULL COMMENT '平台SKU',
  source_site_name VARCHAR(100) NOT NULL COMMENT 'Excel原始站点',
  site_name VARCHAR(100) NOT NULL COMMENT '标准站点名称',
  profit_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '利润人民币',
  product_sales_amount_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '商品销售额人民币',
  shipping_receivable_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '应收运费人民币',
  refund_amount_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '退款金额人民币',
  net_revenue_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '利润率分母，商品销售额加应收运费减退款金额',
  import_batch_id VARCHAR(64) NOT NULL COMMENT '利润表导入批次ID',
  source_row INT NOT NULL COMMENT '来源Excel行号',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_esa_profit_batch_row (import_batch_id,source_row),
  KEY idx_esa_profit_match (payment_date,platform_order_no,inventory_sku),
  KEY idx_esa_profit_sku_site_date (inventory_sku,site_name,payment_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DWD-eBay SKU分析订单利润清洗明细';

CREATE TABLE IF NOT EXISTS dws_ebay_sku_analysis_profit_daily (
  payment_date DATE NOT NULL COMMENT '付款日期',
  stat_month CHAR(7) NOT NULL COMMENT '付款月份，格式YYYY-MM',
  site_name VARCHAR(100) NOT NULL COMMENT '标准站点名称',
  inventory_sku VARCHAR(128) NOT NULL COMMENT '标准库存SKU',
  profit_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '当日利润人民币汇总',
  product_sales_amount_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '当日商品销售额人民币汇总',
  shipping_receivable_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '当日应收运费人民币汇总',
  refund_amount_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '当日退款金额人民币汇总',
  net_revenue_cny DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '当日净收入人民币，商品销售额加应收运费减退款金额',
  source_row_count INT NOT NULL DEFAULT 0 COMMENT '参与汇总的利润明细行数',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (payment_date,site_name,inventory_sku),
  KEY idx_esa_profit_daily_sku_site_date (inventory_sku,site_name,payment_date),
  KEY idx_esa_profit_daily_month (stat_month)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DWS-eBay SKU分析订单利润日汇总';
