-- AMZ-SOP售后链路：订单利润、售后订单、分类维表与最终汇总。
-- 可重复执行，不删除现有数据。

CREATE TABLE IF NOT EXISTS ods_amz_sop_sales_daily (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    period_start DATE NOT NULL COMMENT '统计区间开始日期（含）',
    period_end DATE NOT NULL COMMENT '统计区间结束日期（含）',
    sid VARCHAR(32) NOT NULL COMMENT '领星Amazon店铺ID',
    store_name VARCHAR(255) NULL COMMENT '店铺中文名称',
    data_source VARCHAR(20) NOT NULL COMMENT '数据来源：AMZ-EU/AMZ-US1/AMZ-US2等',
    seller_sku VARCHAR(255) NOT NULL COMMENT 'Amazon店铺SKU（MSKU）',
    local_sku VARCHAR(255) NULL COMMENT '领星本地SKU',
    asin VARCHAR(64) NULL COMMENT 'Amazon ASIN',
    currency_code VARCHAR(16) NOT NULL COMMENT '订单币种',
    volume DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '统计区间销量',
    gross_profit DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '统计区间毛利润',
    amount DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '统计区间销售额',
    refund_amount DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '统计区间退款金额',
    source_hash CHAR(64) NOT NULL COMMENT '源数据关键字段哈希',
    sync_batch_id VARCHAR(64) NOT NULL COMMENT '同步批次ID',
    pulled_at DATETIME NOT NULL COMMENT '从领星拉取时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_amz_sop_sales_period (period_start,period_end,sid,seller_sku,currency_code),
    KEY idx_amz_sop_sales_sku_period (local_sku,period_start,period_end),
    KEY idx_amz_sop_sales_source_period (data_source,period_start,period_end),
    KEY idx_amz_sop_sales_batch (sync_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='ODS-AMZ SOP订单利润区间快照';

CREATE TABLE IF NOT EXISTS dwd_amz_sop_sales_daily (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    period_start DATE NOT NULL COMMENT '统计区间开始日期（含）',
    period_end DATE NOT NULL COMMENT '统计区间结束日期（含）',
    sid VARCHAR(32) NOT NULL COMMENT '领星Amazon店铺ID',
    store_name VARCHAR(255) NULL COMMENT '店铺中文名称',
    data_source VARCHAR(20) NOT NULL COMMENT '数据来源：AMZ-EU/AMZ-US1/AMZ-US2等',
    business_sku VARCHAR(255) NOT NULL COMMENT '清洗后的业务SKU',
    seller_sku VARCHAR(255) NOT NULL COMMENT 'Amazon店铺SKU（MSKU）',
    asin VARCHAR(64) NULL COMMENT 'Amazon ASIN',
    currency_code VARCHAR(16) NOT NULL COMMENT '订单币种',
    volume DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '统计区间销量',
    gross_profit DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '统计区间毛利润',
    amount DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '统计区间销售额',
    refund_amount DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '统计区间退款金额',
    sync_batch_id VARCHAR(64) NOT NULL COMMENT '同步批次ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_dwd_amz_sop_sales (period_start,period_end,sid,business_sku,seller_sku,currency_code),
    KEY idx_dwd_amz_sop_sales_period (period_start,period_end,data_source,business_sku),
    KEY idx_dwd_amz_sop_sales_batch (sync_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='DWD-AMZ SOP清洗后的区间销量';

CREATE TABLE IF NOT EXISTS ods_amz_sop_after_sales (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    source_key VARCHAR(128) NOT NULL COMMENT '售后商品明细技术唯一键',
    amazon_order_id VARCHAR(64) NOT NULL COMMENT 'Amazon订单号；增量更新按订单整体覆盖',
    sid VARCHAR(32) NOT NULL COMMENT '领星Amazon店铺ID',
    store_name VARCHAR(255) NULL COMMENT '店铺中文名称',
    data_source VARCHAR(20) NOT NULL COMMENT '数据来源：AMZ-EU/AMZ-US1/AMZ-US2等',
    local_sku VARCHAR(255) NULL COMMENT '领星本地SKU',
    msku VARCHAR(255) NULL COMMENT 'Amazon店铺SKU（MSKU）',
    asin VARCHAR(64) NULL COMMENT 'Amazon ASIN',
    after_type VARCHAR(20) NOT NULL COMMENT '售后类型：退款/退货/换货',
    after_quantity DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '售后数量',
    after_reason TEXT NULL COMMENT '领星返回的售后原因原文',
    return_status VARCHAR(255) NULL COMMENT '领星返回的退货状态原文',
    inventory_attributes VARCHAR(255) NULL COMMENT '领星返回的库存属性原文',
    buyers_note TEXT NULL COMMENT '领星返回的买家备注原文',
    after_time DATETIME NULL COMMENT '商品明细售后时间',
    data_update_time DATETIME NULL COMMENT '商品明细源数据更新时间',
    item_identifier VARCHAR(255) NULL COMMENT '领星售后商品唯一标识',
    md5_v2 VARCHAR(128) NULL COMMENT '领星售后商品压缩唯一标识',
    source_hash CHAR(64) NOT NULL COMMENT '源数据关键字段哈希',
    sync_batch_id VARCHAR(64) NOT NULL COMMENT '同步批次ID',
    pulled_at DATETIME NOT NULL COMMENT '从领星拉取时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_amz_sop_after_source (source_key),
    KEY idx_amz_sop_after_time (after_time),
    KEY idx_amz_sop_after_update (data_update_time),
    KEY idx_amz_sop_after_order (amazon_order_id),
    KEY idx_amz_sop_after_sku (local_sku,msku),
    KEY idx_amz_sop_after_batch (sync_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='ODS-AMZ SOP售后订单商品明细';

CREATE TABLE IF NOT EXISTS dim_amz_sop_after_sales_category (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    big_category VARCHAR(50) NOT NULL COMMENT '售后原因大类',
    small_category VARCHAR(100) NOT NULL COMMENT '售后原因小类',
    responsible_party VARCHAR(100) NULL COMMENT '责任部门或责任方',
    classification_description TEXT NULL COMMENT '分类判定说明',
    priority INT NOT NULL DEFAULT 100 COMMENT '规则匹配优先级，数值越小越优先',
    rule_version VARCHAR(32) NOT NULL DEFAULT '2026-08-07' COMMENT '分类规则版本',
    enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用：1启用，0停用',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_amz_sop_category (big_category,small_category),
    KEY idx_amz_sop_category_enabled (enabled,priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='DIM-AMZ SOP售后分类规则';

CREATE TABLE IF NOT EXISTS dim_amz_sop_classification_cache (
    classification_hash CHAR(64) NOT NULL COMMENT '四项售后原文组合哈希',
    after_reason TEXT NULL COMMENT '售后原因原文',
    return_status VARCHAR(255) NULL COMMENT '退货状态原文',
    inventory_attributes VARCHAR(255) NULL COMMENT '库存属性原文',
    buyers_note TEXT NULL COMMENT '买家备注原文',
    after_reason_zh TEXT NULL COMMENT '售后原因中文翻译',
    return_status_zh VARCHAR(255) NULL COMMENT '退货状态中文翻译',
    inventory_attributes_zh VARCHAR(255) NULL COMMENT '库存属性中文翻译',
    buyers_note_zh TEXT NULL COMMENT '买家备注中文翻译',
    big_category VARCHAR(50) NOT NULL COMMENT 'AI或规则判定的售后大类',
    small_category VARCHAR(100) NOT NULL COMMENT 'AI或规则判定的售后小类',
    confidence DECIMAL(8,6) NOT NULL DEFAULT 0 COMMENT '分类置信度',
    classify_method VARCHAR(20) NOT NULL COMMENT '分类方式：规则/AI/兜底',
    model_name VARCHAR(100) NULL COMMENT 'AI模型名称',
    rule_version VARCHAR(32) NOT NULL COMMENT '分类规则版本',
    evidence TEXT NULL COMMENT '分类依据说明',
    response_json LONGTEXT NULL COMMENT 'AI分类响应JSON',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (classification_hash),
    KEY idx_amz_sop_cache_category (big_category,small_category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='DIM-AMZ SOP售后AI分类缓存';

CREATE TABLE IF NOT EXISTS dwd_amz_sop_after_sales (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    source_key VARCHAR(128) NOT NULL COMMENT '售后商品明细技术唯一键',
    amazon_order_id VARCHAR(64) NOT NULL COMMENT 'Amazon订单号',
    sid VARCHAR(32) NOT NULL COMMENT '领星Amazon店铺ID',
    store_name VARCHAR(255) NULL COMMENT '店铺中文名称',
    data_source VARCHAR(20) NOT NULL COMMENT '数据来源：AMZ-EU/AMZ-US1/AMZ-US2等',
    business_sku VARCHAR(255) NOT NULL COMMENT '清洗后的业务SKU',
    msku VARCHAR(255) NULL COMMENT 'Amazon店铺SKU（MSKU）',
    asin VARCHAR(64) NULL COMMENT 'Amazon ASIN',
    after_type VARCHAR(20) NOT NULL COMMENT '售后类型：退款/退货/换货',
    coexist_flag TINYINT NOT NULL DEFAULT 0 COMMENT '同订单退款和退货是否并存：1是，0否',
    after_quantity DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '售后数量',
    after_reason TEXT NULL COMMENT '售后原因原文',
    return_status VARCHAR(255) NULL COMMENT '退货状态原文',
    inventory_attributes VARCHAR(255) NULL COMMENT '库存属性原文',
    buyers_note TEXT NULL COMMENT '买家备注原文',
    after_reason_zh TEXT NULL COMMENT '售后原因中文翻译',
    return_status_zh VARCHAR(255) NULL COMMENT '退货状态中文翻译',
    inventory_attributes_zh VARCHAR(255) NULL COMMENT '库存属性中文翻译',
    buyers_note_zh TEXT NULL COMMENT '买家备注中文翻译',
    after_sales_note TEXT NULL COMMENT '四项售后信息合并后的中文备注',
    big_category VARCHAR(50) NOT NULL COMMENT '售后原因大类',
    small_category VARCHAR(100) NOT NULL COMMENT '售后原因小类',
    classify_method VARCHAR(20) NOT NULL COMMENT '分类方式：规则/AI/兜底',
    confidence DECIMAL(8,6) NOT NULL DEFAULT 0 COMMENT '分类置信度',
    merged_from_source_key VARCHAR(128) NULL COMMENT '退款吸收的退货明细技术键',
    after_time DATETIME NULL COMMENT '商品明细售后时间',
    data_update_time DATETIME NULL COMMENT '商品明细源数据更新时间',
    sync_batch_id VARCHAR(64) NOT NULL COMMENT '同步批次ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_dwd_amz_sop_after (source_key),
    KEY idx_dwd_amz_sop_after_period (after_time,big_category),
    KEY idx_dwd_amz_sop_after_sku (business_sku,data_source),
    KEY idx_dwd_amz_sop_after_order (amazon_order_id,business_sku),
    KEY idx_dwd_amz_sop_after_batch (sync_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='DWD-AMZ SOP已翻译分类及合并的售后明细';

CREATE TABLE IF NOT EXISTS dws_amz_sop_after_sales_summary (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    period_start DATE NOT NULL COMMENT '统计区间开始日期（含）',
    period_end DATE NOT NULL COMMENT '统计区间结束日期（含）',
    big_category VARCHAR(50) NOT NULL COMMENT '售后原因大类',
    small_category VARCHAR(100) NOT NULL COMMENT '售后原因小类',
    business_sku VARCHAR(255) NOT NULL COMMENT '清洗后的业务SKU',
    order_count INT NOT NULL DEFAULT 0 COMMENT '售后订单数量',
    order_numbers LONGTEXT NULL COMMENT '去重后累计订单号',
    source_after_quantity_text TEXT NULL COMMENT '各数据来源售后数量文本',
    source_sales_volume_text TEXT NULL COMMENT '各数据来源销量文本',
    after_quantity DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '售后总数量',
    sales_volume DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '销量总数量',
    after_sales_rate DECIMAL(16,8) NOT NULL DEFAULT 0 COMMENT '售后率=售后数量/销量',
    sync_batch_id VARCHAR(64) NOT NULL COMMENT '同步批次ID',
    generated_at DATETIME NOT NULL COMMENT '汇总生成时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_amz_sop_summary (period_start,period_end,big_category,small_category,business_sku),
    KEY idx_amz_sop_summary_period (period_end,period_start),
    KEY idx_amz_sop_summary_category (big_category,small_category),
    KEY idx_amz_sop_summary_quantity (period_start,period_end,after_quantity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='DWS-AMZ SOP售后率最终汇总';

INSERT IGNORE INTO dim_amz_sop_after_sales_category
    (big_category,small_category,responsible_party,classification_description,priority)
VALUES
('产品质量问题','产品质量差','采购部','产品质量差、做工差、与合理质量预期不符。',10),
('产品质量问题','产品无法使用','采购部','产品存在功能故障或无法正常使用。',20),
('国内物流部','组套产品漏发','国内物流部','组合或套装商品缺件、漏发其中一个产品。',30),
('供应商加强包装','到货破损','国内物流部&采购部','运输或包装防护不足导致到货破损。',40),
('国内物流部','产品缺少配件','国内物流部','主商品到达但包装内配件缺失。',50),
('不适配','产品不适配','开发部','尺寸、型号、车型、接口等不匹配。',60),
('不适配','listing货描不符','开发部','实物与Listing标题、图片或描述不一致。',70),
('其他','我方取消订单','运营部','由我方主动取消订单。',80),
('补偿','补差价','运营部','价格差、运费差等差额补偿。',90),
('补偿','返折扣优惠','运营部','通过退款或返现提供折扣优惠。',100),
('其他','其他','运营部','无法从现有信息可靠判断的情况。',110),
('补偿','客户不满意补偿','运营部','为处理客户不满而给予部分补偿。',120),
('退货已损坏','退货未上架','海外仓','退回商品损坏或不可售，未重新上架。',130),
('海外仓问题','海外仓发错货','海外仓','海外仓错发SKU、数量或包裹。',140),
('物流商问题','物流异常退回','海外物流商','运输异常导致包裹退回。',150),
('物流商问题','物流断更','海外物流商','物流轨迹长时间无更新。',160),
('物流商问题','物流延迟补偿','返折扣优惠','物流延误产生的补偿。',170),
('客户自身原因','客户主观退换货','客户自身','不喜欢、不需要、改变主意等主观原因。',180),
('客户自身原因','客户主动取消订单','客户自身','客户主动取消订单。',190),
('客户自身原因','客户拒收包裹','客户自身','客户拒收或未领取包裹。',200);
