-- Python database; intentionally no USE, so startup migrations honor MYSQL_DATABASE.
CREATE TABLE IF NOT EXISTS ods_lingxing_amz_listing_latest (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键，非业务唯一键',
  `listing_id` LONGTEXT NULL COMMENT '亚马逊刊登ID，接口可能返回空值',
  `sid` BIGINT NOT NULL COMMENT '店铺id',
  `marketplace` LONGTEXT NULL COMMENT '国家',
  `seller_sku` LONGTEXT NULL COMMENT '卖家SKU（MSKU），保留原始大小写和后缀',
  `fnsku` LONGTEXT NULL COMMENT '亚马逊物流库存编码（FNSKU）',
  `asin` LONGTEXT NULL COMMENT '亚马逊商品编码（ASIN）',
  `parent_asin` LONGTEXT NULL COMMENT '父商品编码（父ASIN）',
  `small_image_url` LONGTEXT NULL COMMENT '商品缩略图地址',
  `status` TINYINT NOT NULL COMMENT '状态：0 停售，1 在售',
  `is_delete` TINYINT NOT NULL COMMENT '是否删除：0 否，1 是',
  `item_name` LONGTEXT NULL COMMENT '标题',
  `local_sku` LONGTEXT NULL COMMENT '领星本地产品SKU，未配对时可能为空',
  `local_name` LONGTEXT NULL COMMENT '领星本地产品品名',
  `currency_code` LONGTEXT NULL COMMENT '接口原币种代码；金额未换算人民币',
  `price` LONGTEXT NULL COMMENT '价格【不包含促销，运费，积分】',
  `landed_price` LONGTEXT NULL COMMENT '总价【包含了促销、运费、积分】',
  `listing_price` LONGTEXT NULL COMMENT '优惠价',
  `shipping` LONGTEXT NULL COMMENT '运费',
  `points` LONGTEXT NULL COMMENT '积分，日本站才有',
  `quantity` LONGTEXT NULL COMMENT 'FBM库存',
  `afn_fulfillable_quantity` LONGTEXT NULL COMMENT 'FBA可售',
  `afn_unsellable_quantity` LONGTEXT NULL COMMENT 'FBA不可售',
  `reserved_fc_transfers` LONGTEXT NULL COMMENT '待调仓',
  `reserved_fc_processing` LONGTEXT NULL COMMENT '调仓中',
  `reserved_customerorders` LONGTEXT NULL COMMENT '待发货',
  `afn_inbound_shipped_quantity` LONGTEXT NULL COMMENT '在途',
  `afn_inbound_working_quantity` LONGTEXT NULL COMMENT '计划入库',
  `afn_inbound_receiving_quantity` LONGTEXT NULL COMMENT '入库中',
  `open_date` LONGTEXT NULL COMMENT '商品创建时间',
  `open_date_display` LONGTEXT NULL COMMENT '商品创建时间，格式：Y-m-d H:i:s+时区',
  `listing_update_date` LONGTEXT NULL COMMENT 'All Listing报表更新时间 (注意：此为零时区时间)',
  `seller_rank` LONGTEXT NULL COMMENT '排名',
  `seller_brand` LONGTEXT NULL COMMENT '亚马逊品牌',
  `seller_category` LONGTEXT NULL COMMENT '排名所属的类别(后续不再维护，改用seller_category_new)',
  `review_num` LONGTEXT NULL COMMENT '评论条数',
  `last_star` LONGTEXT NULL COMMENT '星级评分',
  `fulfillment_channel_type` LONGTEXT NULL COMMENT '配送方式',
  `principal_info` JSON NULL COMMENT '领星接口返回的负责人信息数组，含用户ID和姓名；不替代本系统月度负责人规则',
  `seller_category_new` JSON NULL COMMENT '排名所属类别的原始JSON数组',
  `pair_update_time` LONGTEXT NULL COMMENT '配对更新时间 (注意：此为北京时间)',
  `first_order_time` LONGTEXT NULL COMMENT '首单时间，格式：Y-m-d',
  `on_sale_time` LONGTEXT NULL COMMENT '开售时间，格式：Y-m-d',
  `store_type` LONGTEXT NULL COMMENT '商品类型，1-非低价商店 ，2-低价商店商品',
  `total_volume` LONGTEXT NULL COMMENT '近7天销量，非历史累计销量',
  `yesterday_volume` LONGTEXT NULL COMMENT '销量-昨天',
  `fourteen_volume` LONGTEXT NULL COMMENT '销量-14天',
  `thirty_volume` LONGTEXT NULL COMMENT '销量-30天',
  `yesterday_amount` LONGTEXT NULL COMMENT '销售额-昨天',
  `seven_amount` LONGTEXT NULL COMMENT '销售额-7天',
  `fourteen_amount` LONGTEXT NULL COMMENT '销售额-14天',
  `thirty_amount` LONGTEXT NULL COMMENT '销售额-30天',
  `average_seven_volume` LONGTEXT NULL COMMENT '日均销量-7日',
  `average_fourteen_volume` LONGTEXT NULL COMMENT '日均销量-14日',
  `average_thirty_volume` LONGTEXT NULL COMMENT '日均销量-30日',
  `dimension_info` JSON NULL COMMENT '商品及包装尺寸、重量与单位的原始JSON数组',
  `small_rank` JSON NULL COMMENT '商品小类排名JSON数组，含类别和名次',
  `global_tags` JSON NULL COMMENT '全局标签JSON数组，含标签ID、名称和颜色',
  `variant` JSON NULL COMMENT '变体属性JSON数组，含属性名和属性值',
  `source_row_no` BIGINT UNSIGNED NOT NULL COMMENT '当前批次行号，从1开始；保留原始重复行及大小写差异',
  `request_sids` VARCHAR(1000) NOT NULL COMMENT '本页请求的店铺ID列表，英文逗号分隔',
  `source_offset` BIGINT UNSIGNED NOT NULL COMMENT '本页请求的分页偏移量offset，从0开始',
  `source_row_in_page` INT UNSIGNED NOT NULL COMMENT '原始记录在本页的位置，从1开始',
  `api_total` BIGINT UNSIGNED NOT NULL COMMENT '接口返回的本组请求店铺记录总数，非单页行数',
  `api_request_id` LONGTEXT NULL COMMENT '领星接口本页响应的请求链路ID',
  `api_response_time` LONGTEXT NULL COMMENT '领星接口本页响应时间，保留原始字符串',
  `response_meta_json` JSON NOT NULL COMMENT '本页原始响应除data外的完整字段，含状态码与请求信息',
  `sync_batch_id` VARCHAR(64) NOT NULL COMMENT '本次全量同步批次ID，与成功发布状态表关联',
  `pulled_at` DATETIME NOT NULL COMMENT '本批开始拉取时间，北京时间',
  `raw_json` JSON NOT NULL COMMENT '刊登完整原始JSON，含全部嵌套字段及接口未来新增字段',
  PRIMARY KEY (id),
  UNIQUE KEY uk_source_row (source_row_no),
  KEY idx_status_sid (status,sid),
  KEY idx_sid_seller (sid,seller_sku(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
COMMENT='领星AMZ刊登原始数据；只保留最新完整批次，不以sid+SKU或可能为空的listing_id限制原始行';
CREATE TABLE IF NOT EXISTS ods_lingxing_amz_listing_state (
  `id` TINYINT UNSIGNED NOT NULL COMMENT '单行发布状态主键，固定为1',
  `sync_batch_id` VARCHAR(64) NOT NULL COMMENT '本次全量同步批次ID，与成功发布状态表关联',
  `row_count` BIGINT UNSIGNED NOT NULL COMMENT '已成功发布批次的原始记录总行数，含非在售及已删除',
  `shop_count` INT UNSIGNED NOT NULL COMMENT '已成功发布批次请求的店铺总数',
  `pulled_at` DATETIME NOT NULL COMMENT '本批开始拉取时间，北京时间',
  `published_at` DATETIME NOT NULL COMMENT '本批完整数据成功发布时间，北京时间',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AMZ原始刊登已成功发布的单行状态；与原始表同一事务替换';
INSERT INTO scheduler_task (task_code,task_name,cron_expression,enabled,description)
VALUES ('lingxing_amz_listing_raw_sync','领星-AMZ刊登原始数据每周同步','0 0 10 ? * THU',1,
'每周四北京时间10:00；仅sid及分页，全字段原始数据；全量拉取校验后事务覆盖；不改Java补货源表，Quartz为唯一计时器。')
ON DUPLICATE KEY UPDATE task_name=VALUES(task_name),cron_expression=VALUES(cron_expression),description=VALUES(description);
