CREATE TABLE IF NOT EXISTS tax_refund_export_details (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键',
    declaration_month CHAR(6) NOT NULL COMMENT '申报年月，格式YYYYMM，对应Excel“申报年月”',
    declaration_batch VARCHAR(20) NOT NULL COMMENT '申报批次，保留Excel中的前导零',
    sequence_no VARCHAR(20) NOT NULL COMMENT '申报明细序号，保留Excel中的前导零',
    correlation_no VARCHAR(50) NOT NULL COMMENT '出口与进货明细的关联号，也是本表增量更新唯一业务键',
    contract_no VARCHAR(100) NULL COMMENT '由出口发票号码推导的FBA或RVG合同号',
    export_invoice_no VARCHAR(100) NOT NULL COMMENT '出口发票号码',
    customs_declaration_no VARCHAR(100) NOT NULL COMMENT '出口货物报关单号，包含报关单商品项号',
    agent_export_certificate_no VARCHAR(100) NULL COMMENT '代理出口货物证明号',
    export_date DATE NULL COMMENT '出口日期；按18位报关单号从出口日期表自动匹配',
    export_product_code VARCHAR(30) NOT NULL COMMENT '出口商品代码或海关商品编码',
    export_product_name VARCHAR(500) NOT NULL COMMENT '出口商品名称',
    measurement_unit VARCHAR(50) NOT NULL COMMENT '计量单位',
    export_quantity DECIMAL(20,6) NOT NULL COMMENT '出口数量',
    fob_value_usd DECIMAL(20,4) NOT NULL COMMENT '美元离岸价，币种USD',
    declared_product_code VARCHAR(30) NULL COMMENT '申报商品代码',
    tax_refund_business_type VARCHAR(100) NULL COMMENT '退（免）税业务类型',
    remark TEXT NULL COMMENT 'Excel备注',
    upload_batch_id CHAR(36) NOT NULL COMMENT '本次文件上传批次UUID',
    uploaded_file_name VARCHAR(500) NOT NULL COMMENT '用户上传的原始Excel文件名',
    source_hash CHAR(64) NOT NULL COMMENT '上传文件SHA-256哈希，用于识别重复文件',
    source_sheet VARCHAR(100) NOT NULL DEFAULT 'Sheet1' COMMENT '数据来源Sheet名称',
    source_row INT NOT NULL COMMENT '数据在原Excel中的行号',
    imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据导入时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_export_correlation_no (correlation_no),
    KEY idx_export_upload_row (source_hash, source_row),
    KEY idx_export_contract_no (contract_no),
    KEY idx_export_invoice_no (export_invoice_no),
    KEY idx_export_customs_no (customs_declaration_no),
    KEY idx_export_product_code (export_product_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='出口退（免）税申报明细表，字段依据出口明细Excel Sheet1设计';

CREATE TABLE IF NOT EXISTS tax_refund_purchase_details (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键',
    detail_key VARCHAR(200) NOT NULL COMMENT '进货明细唯一键；MANUAL:关联号或FIFO:出口明细ID:库存批次ID',
    source_type VARCHAR(30) NOT NULL DEFAULT 'MANUAL_EXCEL' COMMENT '数据来源：MANUAL_EXCEL手工Excel或FIFO_INVOICE发票库存分配',
    inventory_allocation_id BIGINT UNSIGNED NULL COMMENT 'FIFO生成行对应的库存扣减流水ID；手工Excel行为NULL',
    allocation_sequence INT NOT NULL DEFAULT 1 COMMENT '同一关联号由多张发票拆分时的FIFO分配顺序，从1开始',
    declaration_month CHAR(6) NOT NULL COMMENT '申报年月，格式YYYYMM，对应Excel“申报年月”',
    declaration_batch VARCHAR(20) NOT NULL COMMENT '申报批次，保留Excel中的前导零',
    sequence_no VARCHAR(20) NOT NULL COMMENT '进货明细序号；原Excel第3列表头为空，系统命名为序号',
    correlation_no VARCHAR(50) NOT NULL COMMENT '与出口明细对应的关联号，也是本表增量更新唯一业务键',
    contract_no VARCHAR(100) NULL COMMENT '根据关联号匹配出口明细后回填的FBA或RVG合同号',
    tax_type VARCHAR(100) NOT NULL COMMENT '税种，例如V|增值税',
    refundable_tax_amount DECIMAL(20,4) NOT NULL COMMENT '可退税额，币种RMB',
    supplier_tax_id VARCHAR(50) NOT NULL COMMENT '供货方纳税人识别号或统一社会信用代码',
    purchase_voucher_no VARCHAR(100) NOT NULL COMMENT '进货凭证号或增值税发票号码',
    invoice_date DATE NOT NULL COMMENT '进货发票开票日期',
    export_product_code VARCHAR(30) NOT NULL COMMENT '对应出口商品代码或海关商品编码',
    export_product_name VARCHAR(500) NOT NULL COMMENT '对应出口商品名称',
    measurement_unit VARCHAR(50) NOT NULL COMMENT '计量单位',
    quantity DECIMAL(20,6) NOT NULL COMMENT '进货数量',
    taxable_amount DECIMAL(20,4) NOT NULL COMMENT '计税金额，币种RMB',
    levy_rate_percent DECIMAL(10,4) NOT NULL COMMENT '征税率百分比数值，例如13表示13%',
    refund_rate_percent DECIMAL(10,4) NOT NULL COMMENT '退税率百分比数值，例如13表示13%',
    remark TEXT NULL COMMENT 'Excel备注',
    upload_batch_id CHAR(36) NOT NULL COMMENT '本次文件上传批次UUID',
    uploaded_file_name VARCHAR(500) NOT NULL COMMENT '用户上传的原始Excel文件名',
    source_hash CHAR(64) NOT NULL COMMENT '上传文件SHA-256哈希，用于识别重复文件',
    source_sheet VARCHAR(100) NOT NULL DEFAULT 'Sheet1' COMMENT '数据来源Sheet名称',
    source_row INT NOT NULL COMMENT '数据在原Excel中的行号',
    imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据导入时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_purchase_detail_key (detail_key),
    UNIQUE KEY uk_purchase_inventory_allocation (inventory_allocation_id),
    KEY idx_purchase_correlation_no (correlation_no),
    KEY idx_purchase_upload_row (source_hash, source_row),
    KEY idx_purchase_contract_no (contract_no),
    KEY idx_purchase_supplier_tax_id (supplier_tax_id),
    KEY idx_purchase_voucher_no (purchase_voucher_no),
    KEY idx_purchase_product_code (export_product_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='进货退税申报明细表，字段依据进货明细Excel Sheet1设计';

CREATE TABLE IF NOT EXISTS foreign_exchange_receipts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键',
    record_sequence INT NOT NULL COMMENT '业务序号；Excel序号为空时按Sheet1数据行顺序生成',
    contract_no VARCHAR(100) NOT NULL COMMENT '合同协议号，对应Excel“合同编号”，与报关单号组成增量更新唯一键',
    customs_declaration_no VARCHAR(100) NOT NULL COMMENT '报关单号，与合同协议号组成增量更新唯一键',
    export_date DATE NULL COMMENT '出口日期',
    export_port VARCHAR(255) NULL COMMENT '出口口岸',
    declared_contract_amount_usd DECIMAL(20,4) NULL COMMENT '报关合同金额，币种USD',
    export_amount_usd DECIMAL(20,4) NULL COMMENT '出口金额，币种USD',
    monthly_exchange_rate DECIMAL(20,6) NULL COMMENT '月度汇率',
    payment_amount_usd DECIMAL(20,4) NULL COMMENT '回款金额，币种USD',
    foreign_exchange_received_usd DECIMAL(20,4) NULL COMMENT '收汇金额，币种USD',
    bank_transaction_no VARCHAR(100) NULL COMMENT '银行核心流水号',
    actual_exchange_rate DECIMAL(20,6) NULL COMMENT '实际汇率',
    settlement_receipt_amount_rmb DECIMAL(20,4) NULL COMMENT '回单结汇金额，币种RMB',
    receipt_date DATE NULL COMMENT '收汇时间',
    difference_usd DECIMAL(20,4) NULL COMMENT '差额，币种USD',
    upload_batch_id CHAR(36) NOT NULL COMMENT '本次文件上传批次UUID',
    uploaded_file_name VARCHAR(500) NOT NULL COMMENT '用户上传的原始Excel文件名',
    source_hash CHAR(64) NOT NULL COMMENT '上传文件SHA-256哈希，用于识别重复文件',
    source_sheet VARCHAR(100) NOT NULL DEFAULT 'Sheet1' COMMENT '数据来源Sheet名称',
    source_row INT NOT NULL COMMENT '数据在原Excel中的行号',
    imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据导入时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_receipt_contract_customs (contract_no, customs_declaration_no),
    KEY idx_receipt_upload_row (source_hash, source_row),
    KEY idx_receipt_contract_no (contract_no),
    KEY idx_receipt_customs_no (customs_declaration_no),
    KEY idx_receipt_transaction_no (bank_transaction_no),
    KEY idx_receipt_date (receipt_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='外汇回款明细表，读取外汇回款汇总表Sheet1前15列，忽略最后一列结汇时间';

CREATE TABLE IF NOT EXISTS purchase_invoice_summary (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键',
    invoice_year SMALLINT UNSIGNED NOT NULL COMMENT '采购发票所属年份；从工作表名称或开票日期识别',
    source_sequence INT NOT NULL COMMENT '来源工作表“序号”，仅用于追溯，不作为增量业务键',
    invoice_identity VARCHAR(100) NOT NULL COMMENT '发票稳定标识；优先使用数电发票号码，否则使用发票代码和发票号码组合',
    invoice_line_no INT NOT NULL COMMENT '同一发票内商品行顺序，从1开始',
    invoice_code VARCHAR(50) NULL COMMENT '来源字段“发票代码”，按文本保存避免前导零丢失',
    invoice_no VARCHAR(50) NULL COMMENT '来源字段“发票号码”，按文本保存避免前导零丢失',
    digital_invoice_no VARCHAR(50) NULL COMMENT '来源字段“数电发票号码”，按文本保存避免精度丢失',
    seller_tax_id VARCHAR(50) NULL COMMENT '销方识别号',
    seller_name VARCHAR(500) NULL COMMENT '销方名称',
    buyer_tax_id VARCHAR(50) NULL COMMENT '购方识别号',
    buyer_name VARCHAR(500) NULL COMMENT '购买方名称',
    invoice_datetime DATETIME NULL COMMENT '开票日期及时间',
    tax_classification_code VARCHAR(100) NULL COMMENT '税收分类编码，按文本保存',
    special_business_type VARCHAR(255) NULL COMMENT '特定业务类型',
    goods_or_service_name VARCHAR(1000) NULL COMMENT '开票品名；已去除星号前的商品大类，例如*发动机*涡轮增压器保存为涡轮增压器',
    specification VARCHAR(500) NULL COMMENT '来源Excel中的原始规格型号',
    resolved_sku VARCHAR(500) NULL COMMENT '完整SKU；优先取原始规格型号，原始值为空时按商品行与备注SKU顺序补全',
    resolved_sku_source VARCHAR(30) NOT NULL DEFAULT 'UNRESOLVED' COMMENT '完整SKU来源：SPECIFICATION原规格、REMARK_ORDERED备注顺序或UNRESOLVED未识别',
    unit VARCHAR(50) NULL COMMENT '计量单位',
    quantity DECIMAL(20,6) NULL COMMENT '商品数量',
    unit_price DECIMAL(24,12) NULL COMMENT '商品不含税单价',
    amount DECIMAL(20,2) NULL COMMENT '商品不含税金额，币种RMB',
    tax_rate VARCHAR(30) NULL COMMENT '税率或征收率原始显示值，例如13%',
    tax_amount DECIMAL(20,2) NULL COMMENT '商品税额，币种RMB',
    total_with_tax DECIMAL(20,2) NULL COMMENT '价税合计，币种RMB',
    invoice_source VARCHAR(100) NULL COMMENT '发票来源',
    invoice_type VARCHAR(100) NULL COMMENT '发票票种',
    invoice_status VARCHAR(100) NULL COMMENT '发票状态',
    is_positive_invoice VARCHAR(50) NULL COMMENT '是否正数发票，保留来源显示值',
    invoice_risk_level VARCHAR(100) NULL COMMENT '发票风险等级',
    issuer VARCHAR(255) NULL COMMENT '开票人',
    remark TEXT NULL COMMENT '来源备注',
    upload_batch_id CHAR(36) NOT NULL COMMENT '本次文件上传批次UUID',
    uploaded_file_name VARCHAR(500) NOT NULL COMMENT '用户上传的原始Excel文件名',
    source_hash CHAR(64) NOT NULL COMMENT '上传文件SHA-256哈希，用于追溯文件版本',
    source_sheet VARCHAR(100) NOT NULL COMMENT '数据来源工作表名称',
    source_row INT NOT NULL COMMENT '数据在原Excel中的行号',
    imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据导入时间',
    PRIMARY KEY (id),
    KEY idx_purchase_summary_year_sequence (invoice_year, source_sequence),
    UNIQUE KEY uk_purchase_summary_invoice_line (invoice_identity, invoice_line_no),
    KEY idx_purchase_summary_digital_no (digital_invoice_no),
    KEY idx_purchase_summary_invoice_no (invoice_no),
    KEY idx_purchase_summary_invoice_date (invoice_datetime),
    KEY idx_purchase_summary_seller_tax_id (seller_tax_id),
    KEY idx_purchase_summary_goods (goods_or_service_name(100)),
    KEY idx_purchase_summary_source (source_hash, source_row)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='采购发票汇总商品明细；读取全部非空工作表并按发票号码整单增量覆盖';

CREATE TABLE IF NOT EXISTS customs_declaration_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '数据库自增主键',
    contract_no VARCHAR(100) NOT NULL COMMENT '报关单页合同协议号；一个合同允许拆分为多份报关资料',
    invoice_no VARCHAR(100) NOT NULL COMMENT 'INVOICE页INV. NO对应的发票号码',
    source_document_key CHAR(64) NOT NULL COMMENT '合同号+源文件名生成的报关资料标识；同文件重传整份覆盖',
    document_total_usd DECIMAL(20,4) NOT NULL COMMENT '该份报关Excel全部商品美元总价；用于匹配回款表报关合同金额',
    customs_match_status VARCHAR(20) NOT NULL DEFAULT 'UNMATCHED' COMMENT '18位报关单匹配状态：MATCHED、UNMATCHED或AMBIGUOUS',
    customs_declaration_no VARCHAR(30) NULL COMMENT '按合同号及报关总金额匹配的18位海关编号',
    declaration_date DATE NULL COMMENT '预留海关申报日期；当前报关Excel初次上传时为空',
    export_date DATE NULL COMMENT '根据合同协议号从外汇回款汇总表自动匹配的出口日期',
    declaration_month CHAR(6) NULL COMMENT '生成出口明细时填写的申报年月，格式YYYYMM；初次上传为空',
    declaration_batch CHAR(3) NULL COMMENT '生成出口明细时填写的三位申报批次；初次上传为空',
    sequence_no CHAR(8) NULL COMMENT '报关单商品项号补足8位后的申报序号；初次上传为空',
    correlation_no VARCHAR(50) NULL COMMENT '申报年月+三位申报批次+八位序号；初次上传为空',
    item_no VARCHAR(20) NOT NULL COMMENT '报关单商品项号，保留原始展示形式',
    product_code VARCHAR(30) NOT NULL COMMENT '从商品编码单元格开头拆分出的海关商品编码',
    product_use TEXT NULL COMMENT '商品编码单元格去除海关编码及末尾重复规格后的商品用途描述',
    product_name VARCHAR(500) NULL COMMENT '从商品名称及规格型号区域拆分出的商品名称',
    specification VARCHAR(500) NULL COMMENT '从商品名称及规格型号区域拆分出的规格或型号',
    quantity_and_unit VARCHAR(255) NULL COMMENT '报关单数量及单位原始值',
    quantity_value DECIMAL(20,6) NULL COMMENT '数量及单位按/拆分后的第一数量，用作出口数量',
    quantity_unit VARCHAR(50) NULL COMMENT '数量及单位按/拆分后的第一单位，用作出口计量单位',
    second_quantity_value DECIMAL(20,6) NULL COMMENT '数量及单位按/拆分后的第二数量，例如法定第二数量或重量',
    second_quantity_unit VARCHAR(50) NULL COMMENT '数量及单位按/拆分后的第二单位，例如千克',
    price_total_currency VARCHAR(255) NULL COMMENT '报关单单价/总价/币制原始值',
    unit_price DECIMAL(24,12) NULL COMMENT '单价/总价/币制按/拆分后的单价',
    total_price DECIMAL(20,4) NULL COMMENT '单价/总价/币制按/拆分后的总价，用作美元离岸价',
    currency VARCHAR(20) NULL COMMENT '单价/总价/币制按/拆分后的币制，例如USD',
    upload_batch_id CHAR(36) NOT NULL COMMENT '本次文件上传批次UUID',
    uploaded_file_name VARCHAR(500) NOT NULL COMMENT '用户上传的原始Excel文件名',
    source_hash CHAR(64) NOT NULL COMMENT '上传文件SHA-256哈希，用于追溯文件版本',
    source_sheet VARCHAR(100) NOT NULL DEFAULT '报关单' COMMENT '商品明细来源工作表名称',
    source_row INT NOT NULL COMMENT '商品数据在原Excel中的行号',
    imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '首次导入时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最近覆盖更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_customs_document_item (source_document_key, item_no),
    UNIQUE KEY uk_customs_declaration_item (customs_declaration_no, item_no),
    KEY idx_customs_contract_no (contract_no),
    KEY idx_customs_invoice_no (invoice_no),
    KEY idx_customs_declaration_no (customs_declaration_no),
    KEY idx_customs_correlation_no (correlation_no),
    KEY idx_customs_product_code (product_code),
    KEY idx_customs_upload_row (source_hash, source_row)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='报关资料商品明细表；同合同多份文件独立保存，匹配后以18位报关单号+项号唯一';

CREATE TABLE IF NOT EXISTS purchase_invoice_inventory (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '发票商品库存批次自增主键',
    invoice_no VARCHAR(30) NOT NULL COMMENT '电子发票号码；与商品序号组成稳定库存批次键',
    invoice_date DATE NOT NULL COMMENT '开票日期；FIFO按此日期从早到晚扣减',
    seller_name VARCHAR(500) NOT NULL COMMENT '销售方名称',
    seller_tax_id VARCHAR(50) NOT NULL COMMENT '销售方统一社会信用代码或纳税人识别号',
    item_sequence INT NOT NULL COMMENT '商品在发票中的序号，从1开始',
    project_name VARCHAR(1000) NOT NULL COMMENT '发票项目名称',
    specification VARCHAR(500) NOT NULL COMMENT '库存匹配值；精确库存保存SKU，通用品名库存保存发票品名',
    normalized_sku VARCHAR(500) NOT NULL COMMENT '去空格并转大写后的库存匹配值',
    inventory_match_type VARCHAR(20) NOT NULL DEFAULT 'SKU' COMMENT '库存匹配类型：SKU精确规格或PRODUCT_NAME通用品名',
    unit VARCHAR(50) NOT NULL COMMENT '发票商品单位；与报关商品计量单位精确匹配',
    original_quantity DECIMAL(20,6) NOT NULL COMMENT '该发票商品原始入库数量',
    available_quantity DECIMAL(20,6) NOT NULL COMMENT '尚未被最终申报文件占用的可用数量',
    unit_price DECIMAL(24,12) NULL COMMENT '发票商品不含税单价',
    original_amount DECIMAL(20,2) NOT NULL COMMENT '该发票商品原始不含税金额',
    available_amount DECIMAL(20,2) NOT NULL COMMENT '尚未分配的不含税金额，用于分摊时控制舍入差异',
    tax_rate VARCHAR(30) NOT NULL COMMENT '发票税率原始值，例如13%',
    original_tax_amount DECIMAL(20,2) NOT NULL COMMENT '该发票商品原始税额',
    available_tax_amount DECIMAL(20,2) NOT NULL COMMENT '尚未分配的税额，用于分摊时控制舍入差异',
    source_hash CHAR(64) NOT NULL COMMENT '来源采购发票汇总Excel的SHA-256哈希',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '库存批次首次创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '库存批次最近更新时间或扣减时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_inventory_invoice_item (invoice_no, item_sequence),
    KEY idx_inventory_fifo (normalized_sku, unit, invoice_date, invoice_no, item_sequence),
    KEY idx_inventory_generic_fifo (inventory_match_type, normalized_sku, unit, invoice_date, invoice_no, item_sequence),
    KEY idx_inventory_available (available_quantity),
    KEY idx_inventory_seller (seller_tax_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='采购发票汇总FIFO库存明细表；每个有效发票商品行形成一个可扣减库存批次';

CREATE TABLE IF NOT EXISTS purchase_inventory_allocations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'FIFO库存扣减流水自增主键',
    generation_id CHAR(36) NOT NULL COMMENT '首次为该出口商品执行库存分配的业务批次UUID',
    export_detail_id BIGINT UNSIGNED NOT NULL COMMENT '被库存覆盖的出口明细ID',
    correlation_no VARCHAR(50) NOT NULL COMMENT '被库存覆盖的出口关联号',
    inventory_id BIGINT UNSIGNED NOT NULL COMMENT '实际扣减的发票库存批次ID',
    allocation_sequence INT NOT NULL COMMENT '同一出口商品跨发票FIFO拆分顺序，从1开始',
    allocated_quantity DECIMAL(20,6) NOT NULL COMMENT '本次从该发票库存扣减的数量',
    allocated_amount DECIMAL(20,2) NOT NULL COMMENT '按扣减数量分摊的不含税金额',
    allocated_tax_amount DECIMAL(20,2) NOT NULL COMMENT '按扣减数量分摊的税额',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '库存扣减成功提交时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_allocation_export_inventory (export_detail_id, inventory_id),
    KEY idx_allocation_generation (generation_id),
    KEY idx_allocation_correlation (correlation_no),
    KEY idx_allocation_inventory (inventory_id),
    CONSTRAINT fk_allocation_export FOREIGN KEY (export_detail_id) REFERENCES tax_refund_export_details(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_allocation_inventory FOREIGN KEY (inventory_id) REFERENCES purchase_invoice_inventory(id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='出口商品与进项发票库存的FIFO扣减流水；同一出口可由多张发票顺序覆盖';

CREATE TABLE IF NOT EXISTS import_jobs (
    job_id CHAR(36) NOT NULL COMMENT '导入任务UUID',
    kind VARCHAR(50) NOT NULL COMMENT '任务类型，例如 customs_folder_import',
    status VARCHAR(30) NOT NULL COMMENT '任务状态：queued/running/completed/completed_with_errors/failed',
    created_at VARCHAR(30) NOT NULL COMMENT '任务创建时间',
    started_at VARCHAR(30) NULL COMMENT '任务开始时间',
    completed_at VARCHAR(30) NULL COMMENT '任务完成时间',
    total_files INT NOT NULL DEFAULT 0 COMMENT '待处理文件数',
    processed_files INT NOT NULL DEFAULT 0 COMMENT '已处理文件数',
    succeeded_files INT NOT NULL DEFAULT 0 COMMENT '成功文件数',
    failed_files INT NOT NULL DEFAULT 0 COMMENT '失败文件数',
    skipped_file_count INT NOT NULL DEFAULT 0 COMMENT '跳过文件数',
    current_file VARCHAR(500) NULL COMMENT '当前处理文件名',
    processed_rows INT NOT NULL DEFAULT 0 COMMENT '累计处理行数',
    inserted_rows INT NOT NULL DEFAULT 0 COMMENT '累计插入行数',
    updated_rows INT NOT NULL DEFAULT 0 COMMENT '累计更新行数',
    replaced_rows INT NOT NULL DEFAULT 0 COMMENT '累计覆盖行数',
    skipped_files_json JSON NULL COMMENT '跳过文件列表',
    results_json JSON NULL COMMENT '成功文件处理结果',
    errors_json JSON NULL COMMENT '失败文件错误列表',
    fatal_error TEXT NULL COMMENT '任务级致命错误',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最近更新时间',
    PRIMARY KEY (job_id),
    KEY idx_import_jobs_kind_status (kind, status),
    KEY idx_import_jobs_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='异步文件导入任务状态表；用于服务重启后恢复任务查询';

CREATE TABLE IF NOT EXISTS lingxing_token (
    id TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '固定单行主键',
    access_token TEXT NULL COMMENT '领星 access_token',
    refresh_token TEXT NULL COMMENT '领星 refresh_token',
    expires_at DATETIME NULL COMMENT 'access_token 过期时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    CONSTRAINT ck_lingxing_token_singleton CHECK (id = 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='领星 OpenAPI token 持久化表';

CREATE TABLE IF NOT EXISTS ods_lingxing_amz_order_profit_raw (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    stat_month CHAR(7) NOT NULL COMMENT '统计月份YYYY-MM',
    sid VARCHAR(32) NULL COMMENT '领星店铺SID',
    seller_sku VARCHAR(128) NULL COMMENT 'MSKU',
    local_sku VARCHAR(255) NULL COMMENT '本地SKU',
    asin VARCHAR(32) NULL COMMENT 'ASIN',
    country VARCHAR(64) NULL COMMENT '国家/站点',
    currency_code VARCHAR(16) NULL COMMENT '币种',
    gross_profit DECIMAL(20,6) NULL COMMENT '毛利润',
    amount DECIMAL(20,6) NULL COMMENT '销售额',
    refund_amount DECIMAL(20,6) NULL COMMENT '退款金额',
    net_sales_amount DECIMAL(20,6) NULL COMMENT '净销售额',
    principal_names VARCHAR(1000) NULL COMMENT '领星负责人',
    sync_batch_id VARCHAR(64) NULL COMMENT '同步批次ID',
    sync_time DATETIME NULL COMMENT '同步时间',
    source_system VARCHAR(32) NOT NULL DEFAULT 'lingxing' COMMENT '来源系统',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (id),
    KEY idx_ods_amz_profit_month (stat_month),
    KEY idx_ods_amz_profit_batch (sync_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='ODS-领星Amazon月度订单利润原始数据';

CREATE TABLE IF NOT EXISTS ods_ebay_monthly_profit_raw (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    stat_month CHAR(7) NOT NULL COMMENT '统计月份YYYY-MM',
    source_file_name VARCHAR(255) NULL COMMENT '来源文件名',
    source_sheet VARCHAR(64) NULL COMMENT '来源Sheet',
    source_row INT NULL COMMENT '来源行',
    sku VARCHAR(255) NOT NULL COMMENT 'SKU',
    brand_code VARCHAR(64) NOT NULL COMMENT '品牌码',
    image_url VARCHAR(1000) NULL COMMENT '图片',
    multi_variant VARCHAR(32) NULL COMMENT '是否多属性',
    gross_profit DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '利润',
    product_sales_amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '商品销售额',
    receivable_shipping_amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '应收运费',
    sales_amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '销售额',
    refund_amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '退款金额',
    net_sales_amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '净销售额',
    import_batch_id VARCHAR(64) NULL COMMENT '导入批次ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (id),
    KEY idx_ods_ebay_profit_month (stat_month),
    KEY idx_ods_ebay_profit_batch (import_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='ODS-eBay月度利润Excel原始数据';

CREATE TABLE IF NOT EXISTS ods_performance_owner_rule_raw (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    platform VARCHAR(20) NOT NULL COMMENT '平台：amazon/ebay',
    stat_month CHAR(7) NOT NULL COMMENT '统计月份YYYY-MM',
    source_file_name VARCHAR(255) NULL COMMENT '来源文件名',
    source_sheet VARCHAR(64) NULL COMMENT '来源Sheet',
    source_row INT NULL COMMENT '来源行',
    group_code VARCHAR(16) NULL COMMENT '业务组别',
    rule_type VARCHAR(32) NULL COMMENT '匹配规则类型',
    match_key VARCHAR(200) NULL COMMENT '匹配键',
    principal_name VARCHAR(100) NULL COMMENT '负责人',
    import_batch_id VARCHAR(64) NULL COMMENT '导入批次ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (id),
    KEY idx_ods_rule_platform_month (platform, stat_month),
    KEY idx_ods_rule_batch (import_batch_id),
    UNIQUE KEY uk_ods_perf_rule (platform,stat_month,group_code,rule_type,match_key),
    KEY idx_ods_rule_structured (platform,stat_month,group_code,rule_type,match_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='ODS-绩效负责人规则Excel原始数据';

CREATE TABLE IF NOT EXISTS dwd_amz_monthly_order_profit (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    stat_month CHAR(7) NOT NULL COMMENT '统计月份YYYY-MM',
    sid VARCHAR(32) NOT NULL COMMENT '领星店铺SID',
    seller_sku VARCHAR(128) NOT NULL COMMENT 'MSKU',
    local_sku VARCHAR(255) NULL COMMENT '本地SKU',
    asin VARCHAR(32) NULL COMMENT 'ASIN',
    country VARCHAR(64) NULL COMMENT '国家',
    currency_code VARCHAR(16) NOT NULL DEFAULT 'CNY' COMMENT '币种',
    gross_profit DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '毛利润',
    amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '销售额',
    refund_amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '退款金额',
    net_sales_amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '净销售额',
    principal_names VARCHAR(1000) NULL COMMENT '领星原始Listing负责人',
    sync_batch_id VARCHAR(64) NULL COMMENT '同步批次ID',
    sync_time DATETIME NULL COMMENT '同步时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_dwd_amz_profit_month_sid_sku (stat_month, sid, seller_sku),
    KEY idx_dwd_amz_profit_month_gross (stat_month, gross_profit),
    KEY idx_dwd_amz_profit_sku (local_sku),
    KEY idx_dwd_amz_profit_asin (asin)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='DWD-Amazon月度订单利润清洗明细';

CREATE TABLE IF NOT EXISTS dwd_ebay_monthly_profit (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    stat_month CHAR(7) NOT NULL COMMENT '统计月份YYYY-MM',
    sku VARCHAR(255) NOT NULL COMMENT 'SKU',
    brand_code VARCHAR(64) NOT NULL COMMENT '品牌码',
    image_url VARCHAR(1000) NULL COMMENT '图片',
    multi_variant VARCHAR(32) NULL COMMENT '是否多属性',
    gross_profit DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '利润',
    product_sales_amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '商品销售额',
    receivable_shipping_amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '应收运费',
    sales_amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '销售额=商品销售额+应收运费',
    refund_amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '退款金额',
    net_sales_amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '净销售额',
    source_file_name VARCHAR(255) NULL COMMENT '来源文件名',
    source_sheet VARCHAR(64) NULL COMMENT '来源Sheet',
    source_row INT NULL COMMENT '来源行',
    import_batch_id VARCHAR(64) NULL COMMENT '导入批次ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (id),
    KEY idx_dwd_ebay_profit_month (stat_month),
    KEY idx_dwd_ebay_profit_brand (stat_month, brand_code),
    KEY idx_dwd_ebay_profit_sku (sku)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='DWD-eBay月度利润清洗明细';

CREATE TABLE IF NOT EXISTS dwd_performance_owner_rule (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    platform VARCHAR(20) NOT NULL COMMENT '平台：amazon/ebay',
    stat_month CHAR(7) NOT NULL COMMENT '统计月份YYYY-MM',
    group_code VARCHAR(16) NOT NULL DEFAULT '' COMMENT '组别：EU/US1/US2，eBay为空',
    rule_type VARCHAR(32) NOT NULL COMMENT '规则类型：BRAND/OTH_CODE/STORE/EBAY_BRAND',
    match_key VARCHAR(200) NOT NULL COMMENT '匹配键',
    principal_name VARCHAR(100) NOT NULL COMMENT '负责人',
    source_file_name VARCHAR(255) NULL COMMENT '来源文件名',
    source_sheet VARCHAR(64) NULL COMMENT '来源Sheet',
    source_row INT NULL COMMENT '来源行',
    import_batch_id VARCHAR(64) NULL COMMENT '导入批次ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_dwd_perf_rule (platform, stat_month, group_code, rule_type, match_key),
    KEY idx_dwd_perf_rule_owner (platform, stat_month, principal_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='DWD-绩效负责人月度匹配规则';

CREATE TABLE IF NOT EXISTS dws_amz_performance_ranking (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    stat_month CHAR(7) NOT NULL COMMENT '统计月份YYYY-MM',
    principal_name VARCHAR(200) NOT NULL COMMENT '负责人',
    gross_profit DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '毛利润',
    amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '销售额',
    refund_amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '退款金额',
    net_sales_amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '净销售额',
    source_rows INT NOT NULL DEFAULT 0 COMMENT '参与计算源行数',
    matched_rows INT NOT NULL DEFAULT 0 COMMENT '有明确负责人行数',
    unmatched_rows INT NOT NULL DEFAULT 0 COMMENT '未分配行数',
    missing_shop_rows INT NOT NULL DEFAULT 0 COMMENT '缺店铺映射行数',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_dws_amz_perf_month_owner (stat_month, principal_name),
    KEY idx_dws_amz_perf_month_gross (stat_month, gross_profit),
    KEY idx_dws_amz_perf_month_net (stat_month, net_sales_amount)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='DWS-Amazon负责人月度绩效排名';

CREATE TABLE IF NOT EXISTS dws_ebay_performance_ranking (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    stat_month CHAR(7) NOT NULL COMMENT '统计月份YYYY-MM',
    principal_name VARCHAR(200) NOT NULL COMMENT '负责人',
    gross_profit DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '毛利润',
    sales_amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '销售额',
    refund_amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '退款金额',
    net_sales_amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '净销售额',
    source_rows INT NOT NULL DEFAULT 0 COMMENT '源行数',
    matched_rows INT NOT NULL DEFAULT 0 COMMENT '有明确负责人行数',
    unmatched_rows INT NOT NULL DEFAULT 0 COMMENT '未分配行数',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_dws_ebay_perf_month_owner (stat_month, principal_name),
    KEY idx_dws_ebay_perf_month_gross (stat_month, gross_profit),
    KEY idx_dws_ebay_perf_month_net (stat_month, net_sales_amount)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='DWS-eBay负责人月度绩效排名';

CREATE TABLE IF NOT EXISTS dws_combined_performance_ranking (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    stat_month CHAR(7) NOT NULL COMMENT '统计月份YYYY-MM',
    principal_name VARCHAR(200) NOT NULL COMMENT '负责人',
    gross_profit DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '综合毛利润',
    net_sales_amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '综合净销售额',
    amz_gross_profit DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT 'Amazon毛利润',
    amz_net_sales_amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT 'Amazon净销售额',
    ebay_gross_profit DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT 'eBay毛利润',
    ebay_net_sales_amount DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT 'eBay净销售额',
    partial TINYINT NOT NULL DEFAULT 0 COMMENT '是否单平台临时结果',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_dws_combined_perf_month_owner (stat_month, principal_name),
    KEY idx_dws_combined_perf_month_gross (stat_month, gross_profit),
    KEY idx_dws_combined_perf_month_net (stat_month, net_sales_amount)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='DWS-AMZ与eBay综合负责人月度绩效排名';

CREATE TABLE IF NOT EXISTS performance_import_batch (
    batch_id VARCHAR(64) NOT NULL COMMENT '导入批次ID',
    import_type VARCHAR(40) NOT NULL COMMENT '导入类型',
    platform VARCHAR(20) NOT NULL COMMENT '平台',
    stat_month CHAR(7) NULL COMMENT '统计月份',
    source_file_name VARCHAR(255) NULL COMMENT '来源文件名',
    file_hash CHAR(64) NULL COMMENT '文件SHA256',
    idempotency_key VARCHAR(200) NULL COMMENT '幂等键',
    status VARCHAR(20) NOT NULL COMMENT '状态',
    total_rows INT NOT NULL DEFAULT 0 COMMENT '总行数',
    inserted_rows INT NOT NULL DEFAULT 0 COMMENT '插入行数',
    updated_rows INT NOT NULL DEFAULT 0 COMMENT '更新行数',
    skipped_rows INT NOT NULL DEFAULT 0 COMMENT '跳过行数',
    operator VARCHAR(64) NULL COMMENT '操作人',
    request_id VARCHAR(128) NULL COMMENT '请求ID',
    error_message TEXT NULL COMMENT '错误摘要',
    started_at DATETIME NULL COMMENT '开始时间',
    completed_at DATETIME NULL COMMENT '完成时间',
    PRIMARY KEY (batch_id),
    UNIQUE KEY uk_perf_import_file (import_type, platform, stat_month, file_hash),
    KEY idx_perf_import_month (platform, stat_month),
    KEY idx_perf_import_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='绩效导入批次审计表';

CREATE TABLE IF NOT EXISTS performance_refresh_run (
    refresh_id VARCHAR(64) NOT NULL COMMENT '刷新ID',
    stat_month CHAR(7) NOT NULL COMMENT '统计月份',
    platform VARCHAR(20) NOT NULL COMMENT '平台：amazon/ebay/combined',
    status VARCHAR(20) NOT NULL COMMENT '状态',
    partial TINYINT NOT NULL DEFAULT 0 COMMENT '是否单平台临时结果',
    source_rows INT NOT NULL DEFAULT 0 COMMENT '源行数',
    matched_rows INT NOT NULL DEFAULT 0 COMMENT '匹配行数',
    unmatched_rows INT NOT NULL DEFAULT 0 COMMENT '未分配行数',
    missing_shop_rows INT NOT NULL DEFAULT 0 COMMENT '缺店铺行数',
    amz_profit_rows INT NOT NULL DEFAULT 0 COMMENT 'AMZ利润行数',
    ebay_profit_rows INT NOT NULL DEFAULT 0 COMMENT 'eBay利润行数',
    amz_ranking_rows INT NOT NULL DEFAULT 0 COMMENT 'AMZ排名行数',
    ebay_ranking_rows INT NOT NULL DEFAULT 0 COMMENT 'eBay排名行数',
    combined_ranking_rows INT NOT NULL DEFAULT 0 COMMENT '综合排名行数',
    trigger_source VARCHAR(40) NULL COMMENT '触发来源',
    request_id VARCHAR(128) NULL COMMENT '请求ID',
    error_message TEXT NULL COMMENT '错误摘要',
    started_at DATETIME NULL COMMENT '开始时间',
    completed_at DATETIME NULL COMMENT '完成时间',
    PRIMARY KEY (refresh_id),
    KEY idx_perf_refresh_month_platform (stat_month, platform),
    KEY idx_perf_refresh_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='绩效刷新运行记录表';

CREATE TABLE IF NOT EXISTS scheduler_task (
    task_code VARCHAR(80) NOT NULL COMMENT '任务编码',
    task_name VARCHAR(200) NOT NULL COMMENT '任务名称',
    cron_expression VARCHAR(100) NOT NULL COMMENT 'Cron表达式',
    enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
    description VARCHAR(1000) NULL COMMENT '说明',
    last_run_at DATETIME NULL COMMENT '最近运行时间',
    next_run_at DATETIME NULL COMMENT '下次运行时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (task_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='内部定时任务定义表';

CREATE TABLE IF NOT EXISTS scheduler_task_run (
    run_id VARCHAR(64) NOT NULL COMMENT '运行ID',
    task_code VARCHAR(80) NOT NULL COMMENT '任务编码',
    status VARCHAR(20) NOT NULL COMMENT '状态',
    stat_month CHAR(7) NULL COMMENT '统计月份',
    trigger_type VARCHAR(40) NOT NULL COMMENT '触发类型：scheduler/manual',
    source_rows INT NOT NULL DEFAULT 0 COMMENT '源行数',
    sync_batch_id VARCHAR(64) NULL COMMENT 'ODS同步批次ID',
    extract_rows INT NOT NULL DEFAULT 0 COMMENT '领星抽取行数',
    ods_rows INT NOT NULL DEFAULT 0 COMMENT 'ODS追加行数',
    inserted_rows INT NOT NULL DEFAULT 0 COMMENT '插入行数',
    updated_rows INT NOT NULL DEFAULT 0 COMMENT '更新行数',
    deleted_rows INT NOT NULL DEFAULT 0 COMMENT '整月替换删除行数',
    skipped_rows INT NOT NULL DEFAULT 0 COMMENT '无效或重复跳过行数',
    amz_ranking_rows INT NOT NULL DEFAULT 0 COMMENT 'AMZ排名行数',
    combined_ranking_rows INT NOT NULL DEFAULT 0 COMMENT '综合排名行数',
    etl_stage VARCHAR(32) NULL COMMENT '当前或失败阶段',
    error_message TEXT NULL COMMENT '错误摘要',
    request_id VARCHAR(128) NULL COMMENT '请求ID',
    started_at DATETIME NULL COMMENT '开始时间',
    completed_at DATETIME NULL COMMENT '完成时间',
    PRIMARY KEY (run_id),
    KEY idx_scheduler_run_task (task_code, started_at),
    KEY idx_scheduler_run_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='内部定时任务运行记录表';


CREATE TABLE IF NOT EXISTS ods_lingxing_amz_fba_inventory_raw (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    pull_month CHAR(7) NOT NULL,
    sync_batch_id VARCHAR(64) NOT NULL,
    source_offset INT NOT NULL DEFAULT 0,
    source_row_no INT NOT NULL DEFAULT 0,
    sid VARCHAR(32) NULL,
    seller_sku VARCHAR(255) NULL,
    sku VARCHAR(255) NULL,
    warehouse_name VARCHAR(255) NULL COMMENT '领星仓库名称',
    seller_group_name VARCHAR(1000) NULL COMMENT '共享仓关联店铺列表',
    share_type TINYINT NULL COMMENT '共享类型：0非共享、1北美共享、2欧洲共享',
    group_code VARCHAR(20) NULL COMMENT '滞销清货组别',
    region_code VARCHAR(10) NULL COMMENT '区域编码',
    region_name VARCHAR(20) NULL COMMENT '区域名称',
    group_match_source VARCHAR(32) NULL COMMENT '组别匹配来源',
    inv_age_0_to_30_days DECIMAL(24,6) NULL,
    inv_age_0_to_30_price DECIMAL(24,6) NULL,
    inv_age_31_to_60_days DECIMAL(24,6) NULL,
    inv_age_31_to_60_price DECIMAL(24,6) NULL,
    inv_age_61_to_90_days DECIMAL(24,6) NULL,
    inv_age_61_to_90_price DECIMAL(24,6) NULL,
    inv_age_0_to_90_days DECIMAL(24,6) NULL,
    inv_age_0_to_90_price DECIMAL(24,6) NULL,
    inv_age_91_to_180_days DECIMAL(24,6) NULL,
    inv_age_91_to_180_price DECIMAL(24,6) NULL,
    inv_age_181_to_270_days DECIMAL(24,6) NULL,
    inv_age_181_to_270_price DECIMAL(24,6) NULL,
    inv_age_271_to_330_days DECIMAL(24,6) NULL,
    inv_age_271_to_330_price DECIMAL(24,6) NULL,
    inv_age_271_to_365_days DECIMAL(24,6) NULL,
    inv_age_271_to_365_price DECIMAL(24,6) NULL,
    inv_age_331_to_365_days DECIMAL(24,6) NULL,
    inv_age_331_to_365_price DECIMAL(24,6) NULL,
    inv_age_365_plus_days DECIMAL(24,6) NULL,
    inv_age_365_plus_price DECIMAL(24,6) NULL,
    pulled_at DATETIME NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_fba_ods_month (pull_month),
    KEY idx_fba_ods_batch (sync_batch_id),
    KEY idx_fba_ods_month_group (pull_month,group_code),
    KEY idx_fba_ods_month_sid_sku (pull_month,sid,seller_sku)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='ODS-领星Amazon FBA库存原始月度批次';

CREATE TABLE IF NOT EXISTS dwd_amz_fba_inventory_monthly_snapshot (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    pull_month CHAR(7) NOT NULL,
    sync_batch_id VARCHAR(64) NOT NULL,
    sid VARCHAR(32) NULL,
    store_name VARCHAR(255) NULL,
    seller_group_name VARCHAR(1000) NULL,
    warehouse_name VARCHAR(255) NULL,
    asin VARCHAR(64) NULL,
    seller_sku VARCHAR(255) NULL,
    fnsku VARCHAR(255) NULL,
    sku VARCHAR(255) NULL,
    product_name VARCHAR(1000) NULL,
    group_code VARCHAR(20) NOT NULL,
    region_code VARCHAR(10) NOT NULL,
    region_name VARCHAR(20) NOT NULL,
    group_match_source VARCHAR(32) NOT NULL,
    inventory_0_90_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
    inventory_0_90_cost DECIMAL(24,6) NOT NULL DEFAULT 0,
    inventory_91_180_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
    inventory_91_180_cost DECIMAL(24,6) NOT NULL DEFAULT 0,
    inventory_181_270_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
    inventory_181_270_cost DECIMAL(24,6) NOT NULL DEFAULT 0,
    inventory_271_365_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
    inventory_271_365_cost DECIMAL(24,6) NOT NULL DEFAULT 0,
    inventory_365_plus_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
    inventory_365_plus_cost DECIMAL(24,6) NOT NULL DEFAULT 0,
    inventory_181_plus_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
    inventory_181_plus_cost DECIMAL(24,6) NOT NULL DEFAULT 0,
    total_inventory_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
    total_inventory_cost DECIMAL(24,6) NOT NULL DEFAULT 0,
    pulled_at DATETIME NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_fba_dwd_month_group (pull_month,group_code),
    KEY idx_fba_dwd_month_sid (pull_month,sid),
    KEY idx_fba_dwd_batch (sync_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='DWD-Amazon FBA库存标准化月度快照';

CREATE TABLE IF NOT EXISTS dws_amz_fba_inventory_age_group (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    pull_month CHAR(7) NOT NULL,
    region_code VARCHAR(10) NOT NULL,
    region_name VARCHAR(20) NOT NULL,
    group_code VARCHAR(20) NOT NULL,
    group_name VARCHAR(50) NOT NULL,
    shop_count INT NOT NULL DEFAULT 0,
    source_row_count INT NOT NULL DEFAULT 0,
    inventory_0_90_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
    inventory_0_90_cost DECIMAL(24,6) NOT NULL DEFAULT 0,
    inventory_91_180_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
    inventory_91_180_cost DECIMAL(24,6) NOT NULL DEFAULT 0,
    inventory_181_plus_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
    inventory_181_plus_cost DECIMAL(24,6) NOT NULL DEFAULT 0,
    total_inventory_qty DECIMAL(24,6) NOT NULL DEFAULT 0,
    total_inventory_cost DECIMAL(24,6) NOT NULL DEFAULT 0,
    pulled_at DATETIME NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_fba_dws_month_group (pull_month,group_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='DWS-Amazon FBA库龄分组汇总';

CREATE TABLE IF NOT EXISTS dwd_ebay_inventory_age_cost_snapshot (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    pull_month CHAR(7) NOT NULL COMMENT '库存库龄快照年月，格式YYYY-MM',
    sync_batch_id VARCHAR(64) NOT NULL COMMENT '本次Python清洗匹配批次ID',
    source_inventory_age_id BIGINT UNSIGNED NOT NULL COMMENT 'Java库谷仓库存库龄ODS明细ID',
    source_goodcang_batch_id VARCHAR(64) NOT NULL COMMENT '谷仓库存库龄源同步批次ID',
    source_product_batch_id VARCHAR(64) NULL COMMENT '领星产品管理源同步批次ID',
    source_product_sku VARCHAR(255) NOT NULL COMMENT '谷仓原始商品SKU，例如JMH-220085-0056',
    sku_middle VARCHAR(255) NOT NULL COMMENT '去掉谷仓SKU首段后的中间SKU，例如220085-0056',
    sku VARCHAR(255) NULL COMMENT '按中间SKU匹配出的领星完整商品SKU',
    warehouse_code VARCHAR(30) NOT NULL COMMENT '谷仓仓库代码',
    warehouse_name VARCHAR(255) NULL COMMENT '谷仓仓库名称',
    transport_country_code CHAR(2) NULL COMMENT '仓库映射出的领星头程费用国家简码',
    inventory_quantity DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '谷仓在库库存数量',
    warehouse_age_days INT NULL COMMENT '谷仓库存库龄天数',
    inventory_age_bucket VARCHAR(20) NOT NULL COMMENT '库龄区间：0_90、91_180、181_PLUS或UNKNOWN',
    cg_price DECIMAL(24,6) NULL COMMENT '领星产品管理采购成本data.cg_price',
    step_price DECIMAL(24,6) NULL COMMENT '领星供应商阶梯价中的正数价格最大值',
    purchase_price DECIMAL(24,6) NULL COMMENT '清洗后单位采购价，优先正数阶梯价，否则取cg_price',
    first_leg_cost DECIMAL(24,6) NULL COMMENT '按谷仓仓库国家匹配的领星单位头程费用',
    unit_landed_cost DECIMAL(24,6) NULL COMMENT '单位货值，等于采购价加头程费用',
    inventory_age_cost DECIMAL(24,6) NULL COMMENT 'SKU库龄成本，等于采购价加头程费用，不乘库存数量',
    match_status VARCHAR(40) NOT NULL COMMENT '匹配状态：MATCHED、PRODUCT_NOT_FOUND、PRODUCT_AMBIGUOUS、PURCHASE_PRICE_NOT_FOUND或TRANSPORT_COST_NOT_FOUND',
    source_pulled_at DATETIME NOT NULL COMMENT '谷仓库存库龄源数据拉取时间',
    pulled_at DATETIME NOT NULL COMMENT '本次Python清洗匹配时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_ebay_inventory_age_month_source (pull_month,source_inventory_age_id),
    KEY idx_ebay_inventory_age_month_bucket (pull_month,inventory_age_bucket),
    KEY idx_ebay_inventory_age_month_sku (pull_month,sku),
    KEY idx_ebay_inventory_age_month_status (pull_month,match_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='DWD-eBay海外仓库存库龄采购价与头程费用匹配明细';

CREATE TABLE IF NOT EXISTS dwd_inventory_age_cost_monthly (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    cost_month CHAR(7) NOT NULL COMMENT '成本所属月份；页面在下一月快照中作为上月成本',
    department_code VARCHAR(50) NOT NULL COMMENT 'Excel部门原值，例如AMZ-US2-MJ',
    group_code VARCHAR(20) NULL COMMENT 'AMZ页面组别；非AMZ部门为空',
    inventory_91_180_cost DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '海外仓90/91-180天货值',
    inventory_181_plus_cost DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '海外仓180/181天以上货值',
    source_file_name VARCHAR(255) NOT NULL,
    source_sheet VARCHAR(100) NOT NULL,
    source_row INT NOT NULL,
    import_batch_id VARCHAR(64) NOT NULL,
    operator VARCHAR(100) NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_inventory_age_cost_month_department (cost_month,department_code),
    KEY idx_inventory_age_cost_month_group (cost_month,group_code),
    KEY idx_inventory_age_cost_batch (import_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='DWD-每月上传的部门海外仓库龄成本快照';

CREATE TABLE IF NOT EXISTS ai_conversations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    conversation_uuid CHAR(36) NOT NULL,
    erp_user_id BIGINT NOT NULL,
    erp_username VARCHAR(100) NOT NULL,
    title VARCHAR(200) NOT NULL DEFAULT '新对话',
    message_count INT UNSIGNED NOT NULL DEFAULT 0,
    last_message_preview VARCHAR(500) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_conversations_uuid (conversation_uuid),
    KEY idx_ai_conversations_user_updated (erp_user_id,updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='AI助手用户会话';

CREATE TABLE IF NOT EXISTS ai_messages (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    conversation_id BIGINT UNSIGNED NOT NULL,
    role VARCHAR(16) NOT NULL,
    content MEDIUMTEXT NOT NULL,
    is_error TINYINT(1) NOT NULL DEFAULT 0,
    request_id VARCHAR(100) NULL,
    model VARCHAR(100) NULL,
    prompt_tokens INT UNSIGNED NOT NULL DEFAULT 0,
    completion_tokens INT UNSIGNED NOT NULL DEFAULT 0,
    total_tokens INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_ai_messages_conversation_created (conversation_id,created_at),
    KEY idx_ai_messages_request (request_id),
    CONSTRAINT fk_ai_messages_conversation
        FOREIGN KEY (conversation_id) REFERENCES ai_conversations (id)
        ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='AI助手会话消息';

CREATE TABLE IF NOT EXISTS `ods_inventory_report_purchase_order_transit` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `stat_month` CHAR(7) NOT NULL COMMENT '月度库存源数据归属年月，格式YYYY-MM',
    `purchase_order_no` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '采购单号',
    `purchase_warehouse` VARCHAR(255) NOT NULL COMMENT '采购仓库，已向下填充合并单元格',
    `purchase_warehouse_detail` VARCHAR(255) NOT NULL COMMENT '采购仓库明细，优先取Excel采购仓库（明细）列',
    `sku` VARCHAR(255) NOT NULL COMMENT '商品SKU',
    `store_name` VARCHAR(255) NULL COMMENT 'Excel店铺名称',
    `unit_price` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '采购单价',
    `pending_arrival_qty` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT '待到货数量',
    `sku_pending_total_cost` DECIMAL(24,6) NOT NULL DEFAULT 0 COMMENT 'SKU待到货总成本，单价乘以待到货数量',
    `product_dimension` VARCHAR(255) NULL COMMENT '产品维度',
    `platform_code` VARCHAR(16) NOT NULL COMMENT '平台编码：AMZ或EBAY',
    `group_code` VARCHAR(32) NOT NULL COMMENT '采购仓库归属组别：EBAY-1、EU、US1、US2或US3',
    `department_code` VARCHAR(32) NOT NULL COMMENT '月度库存汇总部门编码；US3落AMZ-US2-MJ并在页面合并显示',
    `source_file_name` VARCHAR(255) NOT NULL COMMENT '上传的原始文件名',
    `source_sheet` VARCHAR(128) NOT NULL COMMENT 'Excel来源工作表名称',
    `source_row` INT NOT NULL COMMENT 'Excel来源行号',
    `import_batch_id` VARCHAR(64) NOT NULL COMMENT '本次全量替换导入批次ID',
    `imported_by` VARCHAR(64) NULL COMMENT '上传操作人',
    `imported_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '导入时间',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_inventory_purchase_order_batch_row` (`import_batch_id`,`source_row`),
    KEY `idx_inventory_purchase_order_month_department` (`stat_month`,`department_code`),
    KEY `idx_inventory_purchase_order_month_warehouse` (`stat_month`,`purchase_warehouse_detail`),
    KEY `idx_inventory_purchase_order_sku` (`sku`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='ODS-月度库存采购单本地仓在途明细，每次上传全表替换';
