-- 已建表环境补齐76个字段中文注释；无数据增删，不改类型、空值属性和索引。
-- 请避开同步发布时执行；DDL隐式提交，不可用事务回滚。短元数据锁等待超时即失败，可稍后重试。
-- 显式INPLACE/LOCK=NONE，若数据库版本不支持则报错，不自动降级重建表。
USE `date-project`;
SET @amz_listing_comment_lock_wait = @@SESSION.lock_wait_timeout;
SET SESSION lock_wait_timeout = 10;
ALTER TABLE `ods_lingxing_amz_listing_latest`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键，非业务唯一键',
  MODIFY COLUMN `listing_id` LONGTEXT NULL COMMENT '亚马逊刊登ID，接口可能返回空值',
  MODIFY COLUMN `sid` BIGINT NOT NULL COMMENT '店铺id',
  MODIFY COLUMN `marketplace` LONGTEXT NULL COMMENT '国家',
  MODIFY COLUMN `seller_sku` LONGTEXT NULL COMMENT '卖家SKU（MSKU），保留原始大小写和后缀',
  MODIFY COLUMN `fnsku` LONGTEXT NULL COMMENT '亚马逊物流库存编码（FNSKU）',
  MODIFY COLUMN `asin` LONGTEXT NULL COMMENT '亚马逊商品编码（ASIN）',
  MODIFY COLUMN `parent_asin` LONGTEXT NULL COMMENT '父商品编码（父ASIN）',
  MODIFY COLUMN `small_image_url` LONGTEXT NULL COMMENT '商品缩略图地址',
  MODIFY COLUMN `status` TINYINT NOT NULL COMMENT '状态：0 停售，1 在售',
  MODIFY COLUMN `is_delete` TINYINT NOT NULL COMMENT '是否删除：0 否，1 是',
  MODIFY COLUMN `item_name` LONGTEXT NULL COMMENT '标题',
  MODIFY COLUMN `local_sku` LONGTEXT NULL COMMENT '领星本地产品SKU，未配对时可能为空',
  MODIFY COLUMN `local_name` LONGTEXT NULL COMMENT '领星本地产品品名',
  MODIFY COLUMN `currency_code` LONGTEXT NULL COMMENT '接口原币种代码；金额未换算人民币',
  MODIFY COLUMN `price` LONGTEXT NULL COMMENT '价格【不包含促销，运费，积分】',
  MODIFY COLUMN `landed_price` LONGTEXT NULL COMMENT '总价【包含了促销、运费、积分】',
  MODIFY COLUMN `listing_price` LONGTEXT NULL COMMENT '优惠价',
  MODIFY COLUMN `shipping` LONGTEXT NULL COMMENT '运费',
  MODIFY COLUMN `points` LONGTEXT NULL COMMENT '积分，日本站才有',
  MODIFY COLUMN `quantity` LONGTEXT NULL COMMENT 'FBM库存',
  MODIFY COLUMN `afn_fulfillable_quantity` LONGTEXT NULL COMMENT 'FBA可售',
  MODIFY COLUMN `afn_unsellable_quantity` LONGTEXT NULL COMMENT 'FBA不可售',
  MODIFY COLUMN `reserved_fc_transfers` LONGTEXT NULL COMMENT '待调仓',
  MODIFY COLUMN `reserved_fc_processing` LONGTEXT NULL COMMENT '调仓中',
  MODIFY COLUMN `reserved_customerorders` LONGTEXT NULL COMMENT '待发货',
  MODIFY COLUMN `afn_inbound_shipped_quantity` LONGTEXT NULL COMMENT '在途',
  MODIFY COLUMN `afn_inbound_working_quantity` LONGTEXT NULL COMMENT '计划入库',
  MODIFY COLUMN `afn_inbound_receiving_quantity` LONGTEXT NULL COMMENT '入库中',
  MODIFY COLUMN `open_date` LONGTEXT NULL COMMENT '商品创建时间',
  MODIFY COLUMN `open_date_display` LONGTEXT NULL COMMENT '商品创建时间，格式：Y-m-d H:i:s+时区',
  MODIFY COLUMN `listing_update_date` LONGTEXT NULL COMMENT 'All Listing报表更新时间 (注意：此为零时区时间)',
  MODIFY COLUMN `seller_rank` LONGTEXT NULL COMMENT '排名',
  MODIFY COLUMN `seller_brand` LONGTEXT NULL COMMENT '亚马逊品牌',
  MODIFY COLUMN `seller_category` LONGTEXT NULL COMMENT '排名所属的类别(后续不再维护，改用seller_category_new)',
  MODIFY COLUMN `review_num` LONGTEXT NULL COMMENT '评论条数',
  MODIFY COLUMN `last_star` LONGTEXT NULL COMMENT '星级评分',
  MODIFY COLUMN `fulfillment_channel_type` LONGTEXT NULL COMMENT '配送方式',
  MODIFY COLUMN `principal_info` JSON NULL COMMENT '领星接口返回的负责人信息数组，含用户ID和姓名；不替代本系统月度负责人规则',
  MODIFY COLUMN `seller_category_new` JSON NULL COMMENT '排名所属类别的原始JSON数组',
  MODIFY COLUMN `pair_update_time` LONGTEXT NULL COMMENT '配对更新时间 (注意：此为北京时间)',
  MODIFY COLUMN `first_order_time` LONGTEXT NULL COMMENT '首单时间，格式：Y-m-d',
  MODIFY COLUMN `on_sale_time` LONGTEXT NULL COMMENT '开售时间，格式：Y-m-d',
  MODIFY COLUMN `store_type` LONGTEXT NULL COMMENT '商品类型，1-非低价商店 ，2-低价商店商品',
  MODIFY COLUMN `total_volume` LONGTEXT NULL COMMENT '近7天销量，非历史累计销量',
  MODIFY COLUMN `yesterday_volume` LONGTEXT NULL COMMENT '销量-昨天',
  MODIFY COLUMN `fourteen_volume` LONGTEXT NULL COMMENT '销量-14天',
  MODIFY COLUMN `thirty_volume` LONGTEXT NULL COMMENT '销量-30天',
  MODIFY COLUMN `yesterday_amount` LONGTEXT NULL COMMENT '销售额-昨天',
  MODIFY COLUMN `seven_amount` LONGTEXT NULL COMMENT '销售额-7天',
  MODIFY COLUMN `fourteen_amount` LONGTEXT NULL COMMENT '销售额-14天',
  MODIFY COLUMN `thirty_amount` LONGTEXT NULL COMMENT '销售额-30天',
  MODIFY COLUMN `average_seven_volume` LONGTEXT NULL COMMENT '日均销量-7日',
  MODIFY COLUMN `average_fourteen_volume` LONGTEXT NULL COMMENT '日均销量-14日',
  MODIFY COLUMN `average_thirty_volume` LONGTEXT NULL COMMENT '日均销量-30日',
  MODIFY COLUMN `dimension_info` JSON NULL COMMENT '商品及包装尺寸、重量与单位的原始JSON数组',
  MODIFY COLUMN `small_rank` JSON NULL COMMENT '商品小类排名JSON数组，含类别和名次',
  MODIFY COLUMN `global_tags` JSON NULL COMMENT '全局标签JSON数组，含标签ID、名称和颜色',
  MODIFY COLUMN `variant` JSON NULL COMMENT '变体属性JSON数组，含属性名和属性值',
  MODIFY COLUMN `source_row_no` BIGINT UNSIGNED NOT NULL COMMENT '当前批次行号，从1开始；保留原始重复行及大小写差异',
  MODIFY COLUMN `request_sids` VARCHAR(1000) NOT NULL COMMENT '本页请求的店铺ID列表，英文逗号分隔',
  MODIFY COLUMN `source_offset` BIGINT UNSIGNED NOT NULL COMMENT '本页请求的分页偏移量offset，从0开始',
  MODIFY COLUMN `source_row_in_page` INT UNSIGNED NOT NULL COMMENT '原始记录在本页的位置，从1开始',
  MODIFY COLUMN `api_total` BIGINT UNSIGNED NOT NULL COMMENT '接口返回的本组请求店铺记录总数，非单页行数',
  MODIFY COLUMN `api_request_id` LONGTEXT NULL COMMENT '领星接口本页响应的请求链路ID',
  MODIFY COLUMN `api_response_time` LONGTEXT NULL COMMENT '领星接口本页响应时间，保留原始字符串',
  MODIFY COLUMN `response_meta_json` JSON NOT NULL COMMENT '本页原始响应除data外的完整字段，含状态码与请求信息',
  MODIFY COLUMN `sync_batch_id` VARCHAR(64) NOT NULL COMMENT '本次全量同步批次ID，与成功发布状态表关联',
  MODIFY COLUMN `pulled_at` DATETIME NOT NULL COMMENT '本批开始拉取时间，北京时间',
  MODIFY COLUMN `raw_json` JSON NOT NULL COMMENT '刊登完整原始JSON，含全部嵌套字段及接口未来新增字段',
  ALGORITHM=INPLACE, LOCK=NONE;

ALTER TABLE `ods_lingxing_amz_listing_state`
  MODIFY COLUMN `id` TINYINT UNSIGNED NOT NULL COMMENT '单行发布状态主键，固定为1',
  MODIFY COLUMN `sync_batch_id` VARCHAR(64) NOT NULL COMMENT '本次全量同步批次ID，与成功发布状态表关联',
  MODIFY COLUMN `row_count` BIGINT UNSIGNED NOT NULL COMMENT '已成功发布批次的原始记录总行数，含非在售及已删除',
  MODIFY COLUMN `shop_count` INT UNSIGNED NOT NULL COMMENT '已成功发布批次请求的店铺总数',
  MODIFY COLUMN `pulled_at` DATETIME NOT NULL COMMENT '本批开始拉取时间，北京时间',
  MODIFY COLUMN `published_at` DATETIME NOT NULL COMMENT '本批完整数据成功发布时间，北京时间',
  ALGORITHM=INPLACE, LOCK=NONE;
SET SESSION lock_wait_timeout = @amz_listing_comment_lock_wait;
