-- 执行库：Java ERP 的 jmh_data_platform。
-- 来源：模块字段.xls（2026-09-28），4个模块、62个参数值。
-- 可重复执行；不会覆盖已保存的参数。权限复用 list（读取）和 formula（保存）。
-- 本次仅维护参数，不接入现有补货公式。
CREATE TABLE IF NOT EXISTS ebay_replenishment_v2_parameter (
    parameter_key VARCHAR(80) NOT NULL COMMENT '稳定计算参数键',
    module_key VARCHAR(32) NOT NULL,
    numeric_value DECIMAL(18,6) NULL,
    text_value VARCHAR(16) NULL,
    revision BIGINT NOT NULL DEFAULT 0,
    create_by VARCHAR(64) NOT NULL DEFAULT '',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by VARCHAR(64) NOT NULL DEFAULT '',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (parameter_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='eBay补货2.0全局参数';

INSERT INTO ebay_replenishment_v2_parameter
(parameter_key,module_key,numeric_value,text_value,create_by,update_by) VALUES
('prior_days','basic',30,NULL,'SYSTEM','SYSTEM'),
('training_days','basic',92,NULL,'SYSTEM','SYSTEM'),
('stock_factor','basic',1.15,NULL,'SYSTEM','SYSTEM'),
('beta_prior_quantity','basic',5,NULL,'SYSTEM','SYSTEM'),
('test_days','basic',27,NULL,'SYSTEM','SYSTEM'),
('return_ban','basic',0.3,NULL,'SYSTEM','SYSTEM'),
('return_limit','basic',0.15,NULL,'SYSTEM','SYSTEM'),
('return_watch','basic',0.08,NULL,'SYSTEM','SYSTEM'),
('margin_lower','basic',0.1,NULL,'SYSTEM','SYSTEM'),
('margin_upper','basic',0.35,NULL,'SYSTEM','SYSTEM'),
('adi_upper','basic',92,NULL,'SYSTEM','SYSTEM'),
('adi_lower','basic',7,NULL,'SYSTEM','SYSTEM'),
('quality_full_rate','basic',0.03,NULL,'SYSTEM','SYSTEM'),
('evidence_sales','basic',20,NULL,'SYSTEM','SYSTEM'),
('evidence_returns','basic',5,NULL,'SYSTEM','SYSTEM'),
('quality_zero_rate','basic',0.2,NULL,'SYSTEM','SYSTEM'),
('margin_mid_score','basic',40,NULL,'SYSTEM','SYSTEM'),
('negative_margin_grade','basic',NULL,'D','SYSTEM','SYSTEM'),
('quality_floor_score','basic',25,NULL,'SYSTEM','SYSTEM'),
('high_return_stop_rate','basic',0.3,NULL,'SYSTEM','SYSTEM'),
('high_return_evidence_sales','basic',20,NULL,'SYSTEM','SYSTEM'),
('high_return_evidence_returns','basic',10,NULL,'SYSTEM','SYSTEM'),
('hierarchical_prior_days','basic',8,NULL,'SYSTEM','SYSTEM'),
('monthly_holding_rate','basic',0.03,NULL,'SYSTEM','SYSTEM'),
('holding_months','basic',1,NULL,'SYSTEM','SYSTEM'),
('stockout_cost_multiplier','basic',1,NULL,'SYSTEM','SYSTEM'),
('market_growth_multiplier','basic',1.2,NULL,'SYSTEM','SYSTEM'),
('prior_demand_rate','basic',0.02,NULL,'SYSTEM','SYSTEM'),
('pattern_smooth_w7','pattern',0.5,NULL,'SYSTEM','SYSTEM'),
('pattern_smooth_w15','pattern',0.3,NULL,'SYSTEM','SYSTEM'),
('pattern_smooth_w30','pattern',0.2,NULL,'SYSTEM','SYSTEM'),
('pattern_intermittent_w7','pattern',0.35,NULL,'SYSTEM','SYSTEM'),
('pattern_intermittent_w15','pattern',0.35,NULL,'SYSTEM','SYSTEM'),
('pattern_intermittent_w30','pattern',0.3,NULL,'SYSTEM','SYSTEM'),
('pattern_erratic_w7','pattern',0.3,NULL,'SYSTEM','SYSTEM'),
('pattern_erratic_w15','pattern',0.3,NULL,'SYSTEM','SYSTEM'),
('pattern_erratic_w30','pattern',0.4,NULL,'SYSTEM','SYSTEM'),
('pattern_lumpy_w7','pattern',0.2,NULL,'SYSTEM','SYSTEM'),
('pattern_lumpy_w15','pattern',0.3,NULL,'SYSTEM','SYSTEM'),
('pattern_lumpy_w30','pattern',0.5,NULL,'SYSTEM','SYSTEM'),
('pattern_no_sales_w7','pattern',0,NULL,'SYSTEM','SYSTEM'),
('pattern_no_sales_w15','pattern',0,NULL,'SYSTEM','SYSTEM'),
('pattern_no_sales_w30','pattern',0,NULL,'SYSTEM','SYSTEM'),
('grade_S','grade',85,NULL,'SYSTEM','SYSTEM'),
('grade_A','grade',70,NULL,'SYSTEM','SYSTEM'),
('grade_B','grade',55,NULL,'SYSTEM','SYSTEM'),
('grade_C','grade',40,NULL,'SYSTEM','SYSTEM'),
('grade_D','grade',0,NULL,'SYSTEM','SYSTEM'),
('dimension_margin_weight','dimension',0.22,NULL,'SYSTEM','SYSTEM'),
('dimension_margin_enabled','dimension',1,NULL,'SYSTEM','SYSTEM'),
('dimension_demand_weight','dimension',0.16,NULL,'SYSTEM','SYSTEM'),
('dimension_demand_enabled','dimension',1,NULL,'SYSTEM','SYSTEM'),
('dimension_quality_weight','dimension',0.22,NULL,'SYSTEM','SYSTEM'),
('dimension_quality_enabled','dimension',1,NULL,'SYSTEM','SYSTEM'),
('dimension_turnover_weight','dimension',0.16,NULL,'SYSTEM','SYSTEM'),
('dimension_turnover_enabled','dimension',0,NULL,'SYSTEM','SYSTEM'),
('dimension_lifecycle_weight','dimension',0.12,NULL,'SYSTEM','SYSTEM'),
('dimension_lifecycle_enabled','dimension',0,NULL,'SYSTEM','SYSTEM'),
('dimension_amount_weight','dimension',0.07,NULL,'SYSTEM','SYSTEM'),
('dimension_amount_enabled','dimension',0,NULL,'SYSTEM','SYSTEM'),
('dimension_stock_weight','dimension',0.05,NULL,'SYSTEM','SYSTEM'),
('dimension_stock_enabled','dimension',0,NULL,'SYSTEM','SYSTEM')
ON DUPLICATE KEY UPDATE parameter_key=VALUES(parameter_key);

SELECT module_key, COUNT(*) AS parameter_count FROM ebay_replenishment_v2_parameter GROUP BY module_key;
