-- eBay SP 价格批量查询与人工审核任务
-- 仅新增表，不修改或删除现有 eBay 数据。

CREATE TABLE IF NOT EXISTS `ebay_price_audit_task` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '审核任务主键',
  `task_name` varchar(255) NOT NULL COMMENT '任务名称',
  `source_file_name` varchar(255) NOT NULL COMMENT '上传的Excel文件名',
  `site` varchar(8) NOT NULL DEFAULT 'de' COMMENT 'eBay站点：de/uk/us',
  `status` varchar(20) NOT NULL DEFAULT 'QUERYING' COMMENT '任务状态：QUERYING/REVIEWING/COMPLETED',
  `total_rows` int NOT NULL DEFAULT 0 COMMENT 'Excel数据总行数',
  `total_oe` int NOT NULL DEFAULT 0 COMMENT '去重后的OE总数',
  `duplicate_oe` int NOT NULL DEFAULT 0 COMMENT '被忽略的重复OE数',
  `blank_rows` int NOT NULL DEFAULT 0 COMMENT '被忽略的空白行数',
  `processed_oe` int NOT NULL DEFAULT 0 COMMENT '已完成查询的OE数',
  `success_oe` int NOT NULL DEFAULT 0 COMMENT '有查询结果的OE数',
  `empty_oe` int NOT NULL DEFAULT 0 COMMENT '无查询结果的OE数',
  `failed_oe` int NOT NULL DEFAULT 0 COMMENT '查询失败的OE数',
  `reviewed_oe` int NOT NULL DEFAULT 0 COMMENT '已审核或无需审核的OE数',
  `selected_count` int NOT NULL DEFAULT 0 COMMENT '人工选中的商品总数',
  `user_id` bigint NOT NULL COMMENT '创建用户ID',
  `create_by` varchar(64) NOT NULL COMMENT '创建用户名',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `query_end_time` datetime DEFAULT NULL COMMENT '批量查询结束时间',
  PRIMARY KEY (`id`),
  KEY `idx_ebay_audit_task_user_time` (`user_id`, `create_time`),
  KEY `idx_ebay_audit_task_status` (`status`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='eBay价格批量查询审核任务';

CREATE TABLE IF NOT EXISTS `ebay_price_audit_oe` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '任务OE明细主键',
  `task_id` bigint NOT NULL COMMENT '审核任务主键',
  `sort_no` int NOT NULL COMMENT 'Excel中的审核顺序',
  `oe` varchar(128) NOT NULL COMMENT 'OE号',
  `query_status` varchar(20) NOT NULL DEFAULT 'PENDING' COMMENT '查询状态：PENDING/QUERYING/SUCCESS/EMPTY/FAILED',
  `review_status` varchar(20) NOT NULL DEFAULT 'PENDING' COMMENT '审核状态：PENDING/REVIEWED/SKIPPED/NOT_REQUIRED',
  `result_count` int NOT NULL DEFAULT 0 COMMENT '返回的候选商品数',
  `selected_count` int NOT NULL DEFAULT 0 COMMENT '选中的商品数',
  `query_attempts` int NOT NULL DEFAULT 0 COMMENT '查询尝试次数',
  `error_message` varchar(1000) DEFAULT NULL COMMENT '查询失败原因',
  `query_start_time` datetime DEFAULT NULL COMMENT '查询开始时间',
  `query_end_time` datetime DEFAULT NULL COMMENT '查询结束时间',
  `review_by` varchar(64) DEFAULT NULL COMMENT '审核人',
  `review_time` datetime DEFAULT NULL COMMENT '审核时间',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ebay_audit_task_oe` (`task_id`, `oe`),
  KEY `idx_ebay_audit_oe_task_sort` (`task_id`, `sort_no`),
  KEY `idx_ebay_audit_oe_status` (`task_id`, `query_status`, `review_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='eBay价格批量查询OE审核明细';

CREATE TABLE IF NOT EXISTS `ebay_price_audit_item` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '候选商品主键',
  `task_id` bigint NOT NULL COMMENT '审核任务主键',
  `audit_oe_id` bigint NOT NULL COMMENT '任务OE明细主键',
  `rank_no` int NOT NULL COMMENT '当前OE最低价排名',
  `oe` varchar(128) NOT NULL COMMENT 'OE号',
  `item_id` varchar(255) DEFAULT NULL COMMENT 'eBay Browse API商品ID',
  `product_id` varchar(128) DEFAULT NULL COMMENT '用于展示和图片目录的商品ID',
  `title` varchar(1000) DEFAULT NULL COMMENT '商品标题',
  `price_display` varchar(64) DEFAULT NULL COMMENT '带币种的展示价格',
  `price_value` decimal(18,4) NOT NULL DEFAULT 0.0000 COMMENT '用于排序的价格数值',
  `currency` varchar(16) DEFAULT NULL COMMENT '币种',
  `estimated_sold_quantity` int DEFAULT NULL COMMENT 'eBay预计已售数量',
  `condition_name` varchar(128) DEFAULT NULL COMMENT '商品成色',
  `condition_id` varchar(64) DEFAULT NULL COMMENT '商品成色ID',
  `image_urls` longtext COMMENT '商品图片URL列表JSON，仅存储多值图片字段',
  `item_link` varchar(1000) DEFAULT NULL COMMENT '商品链接',
  `seller_name` varchar(255) DEFAULT NULL COMMENT '卖家名称',
  `seller_feedback` varchar(32) DEFAULT NULL COMMENT '卖家好评率',
  `shipping` varchar(128) DEFAULT NULL COMMENT '运费展示值',
  `image_detail_complete` char(1) NOT NULL DEFAULT '0' COMMENT '详情图片是否读取完整：1是/0否',
  `image_detail_error` varchar(1000) DEFAULT NULL COMMENT '详情读取失败原因',
  `selected_flag` char(1) NOT NULL DEFAULT '0' COMMENT '人工审核是否选中：1是/0否',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ebay_audit_oe_item` (`audit_oe_id`, `item_id`),
  KEY `idx_ebay_audit_item_task_selected` (`task_id`, `selected_flag`),
  KEY `idx_ebay_audit_item_oe_rank` (`audit_oe_id`, `rank_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='eBay价格人工审核候选商品';
